import { Router, type Request, type Response, type NextFunction } from 'express';
import bcrypt from 'bcryptjs';
import { createHash, randomBytes } from 'crypto';
import { pool } from '../db.js';
import { requireAdmin } from '../auth.js';
import { getAccountContext } from '../planLimits.js';

const router=Router();
const COOKIE='qtecnico_client_portal';
const CSRF='qtecnico_client_portal_csrf';
const TTL=12*60*60*1000;
const phone=(v:unknown)=>String(v||'').replace(/\D/g,'');
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
function cookies(req:Request){return String(req.headers.cookie||'').split(';').reduce<Record<string,string>>((a,p)=>{const i=p.indexOf('=');if(i>0)a[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim());return a;},{});}
function cookieOptions(httpOnly:boolean){return{httpOnly,secure:true,sameSite:'none' as const,path:'/',maxAge:TTL};}
async function accountId(userId:number){const c=await getAccountContext(userId);if(!c)throw new Error('Conta não encontrada');return c.accountId;}
async function portalAuth(req:Request,res:Response,next:NextFunction){
 try{const token=cookies(req)[COOKIE];if(!token)return res.status(401).json({error:'Acesso ao portal não autenticado'});
 const q=await pool.query(`SELECT s.portal_access_id,a.account_id,a.client_id,a.public_id FROM client_portal_sessions s JOIN client_portal_access a ON a.id=s.portal_access_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>NOW() AND a.active=TRUE LIMIT 1`,[hash(token)]);
 if(!q.rows[0])return res.status(401).json({error:'Sessão do portal expirada'});
 if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const c=cookies(req)[CSRF],h=req.get('X-CSRF-Token');if(!c||!h||c!==h)return res.status(403).json({error:'Proteção CSRF inválida'});}
 (req as any).portal=q.rows[0];next();
 }catch(e){console.error(e);res.status(401).json({error:'Sessão do portal inválida'});}
}
async function event(p:any,type:string,quoteId?:number,orderId?:string){await pool.query('INSERT INTO client_portal_events(account_id,client_id,quote_id,order_id,event_type) VALUES($1,$2,$3,$4,$5)',[p.account_id,p.client_id,quoteId||null,orderId||null,type]);}

router.get('/admin/client/:clientId',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query('SELECT public_id,phone_normalized,active,last_login_at,created_at FROM client_portal_access WHERE account_id=$1 AND client_id=$2',[a,req.params.clientId]);const x=r.rows[0];res.json(x?{enabled:x.active,publicId:x.public_id,phone:x.phone_normalized,lastLoginAt:x.last_login_at,createdAt:x.created_at}:null);}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar acesso do portal'});}});
router.put('/admin/client/:clientId',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId),b=req.body||{};const c=await pool.query('SELECT id,phone FROM clients WHERE id=$1 AND account_id=$2',[req.params.clientId,a]);if(!c.rows[0])return res.status(404).json({error:'Cliente não encontrado'});const normalized=phone(b.phone??c.rows[0].phone);if(normalized.length<10)return res.status(400).json({error:'Informe um telefone válido para o portal'});const existing=await pool.query('SELECT id,public_id,password_hash FROM client_portal_access WHERE account_id=$1 AND client_id=$2',[a,req.params.clientId]);const password=String(b.password||'');if(!existing.rows[0]&&password.length<6)return res.status(400).json({error:'Defina uma senha com pelo menos 6 caracteres'});if(password&&password.length<6)return res.status(400).json({error:'A senha deve ter pelo menos 6 caracteres'});const publicId=existing.rows[0]?.public_id||randomBytes(12).toString('base64url');const passwordHash=password?await bcrypt.hash(password,12):existing.rows[0]?.password_hash;
 await pool.query(`INSERT INTO client_portal_access(account_id,client_id,public_id,phone_normalized,password_hash,active) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(account_id,client_id) DO UPDATE SET phone_normalized=EXCLUDED.phone_normalized,password_hash=EXCLUDED.password_hash,active=EXCLUDED.active,updated_at=NOW()`,[a,req.params.clientId,publicId,normalized,passwordHash,b.enabled!==false]);
 res.json({enabled:b.enabled!==false,publicId,phone:normalized});}catch(e){console.error(e);res.status(500).json({error:'Erro ao configurar portal do cliente'});}});

router.post('/login',async(req,res)=>{try{const publicId=String(req.body?.publicId||''),normalized=phone(req.body?.phone),password=String(req.body?.password||'');const r=await pool.query('SELECT * FROM client_portal_access WHERE public_id=$1 AND active=TRUE LIMIT 1',[publicId]);const a=r.rows[0];const valid=a&&normalized===a.phone_normalized&&await bcrypt.compare(password,a.password_hash);if(!valid){await new Promise(resolve=>setTimeout(resolve,250));return res.status(401).json({error:'Telefone ou senha inválidos'});}const token=randomBytes(32).toString('base64url'),csrf=randomBytes(24).toString('base64url');await pool.query('INSERT INTO client_portal_sessions(portal_access_id,token_hash,expires_at) VALUES($1,$2,$3)',[a.id,hash(token),new Date(Date.now()+TTL)]);await pool.query('UPDATE client_portal_access SET last_login_at=NOW() WHERE id=$1',[a.id]);res.cookie(COOKIE,token,cookieOptions(true));res.cookie(CSRF,csrf,cookieOptions(false));await event(a,'login');res.json({success:true});}catch(e){console.error(e);res.status(500).json({error:'Erro ao acessar o portal'});}});
router.post('/logout',portalAuth,async(req,res)=>{const token=cookies(req)[COOKIE];if(token)await pool.query('UPDATE client_portal_sessions SET revoked_at=NOW() WHERE token_hash=$1',[hash(token)]);res.clearCookie(COOKIE,{path:'/'});res.clearCookie(CSRF,{path:'/'});res.json({success:true});});

router.get('/me',portalAuth,async(req,res)=>{try{const p=(req as any).portal;const c=await pool.query('SELECT id,name,phone,email FROM clients WHERE id=$1 AND account_id=$2',[p.client_id,p.account_id]);const company=await pool.query('SELECT trade_name,legal_name,phone,whatsapp,email,logo_key FROM company_profiles WHERE account_id=$1 LIMIT 1',[p.account_id]).catch(()=>({rows:[]} as any));const cr=company.rows[0]||{};res.json({client:{id:c.rows[0].id,name:c.rows[0].name,phone:c.rows[0].phone,email:c.rows[0].email},company:{name:cr.trade_name||cr.legal_name||'Portal do cliente',phone:cr.phone||'',whatsapp:cr.whatsapp||'',email:cr.email||''}});}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar portal'});}});

router.get('/treatments',portalAuth,async(req,res)=>{try{const p=(req as any).portal;const qs=await pool.query(`SELECT q.*,COALESCE(SUM(i.quantity*i.unit_price),0)::float8 subtotal FROM quotes q LEFT JOIN quote_items i ON i.quote_id=q.id WHERE q.account_id=$1 AND q.client_id=$2 AND q.status<>'draft' GROUP BY q.id ORDER BY q.created_at DESC`,[p.account_id,p.client_id]);const orders=await pool.query('SELECT id,quote_id,type,status,date,priority,description,address FROM orders WHERE account_id=$1 AND client_id=$2 ORDER BY created_at DESC',[p.account_id,p.client_id]);const byQuote=new Map(orders.rows.filter((o:any)=>o.quote_id).map((o:any)=>[Number(o.quote_id),o]));res.json({quotes:qs.rows.map((q:any)=>({id:Number(q.id),number:q.number,status:q.status,issueDate:q.issue_date,validUntil:q.valid_until,title:q.title,description:q.description,serviceAddress:q.service_address,discount:Number(q.discount||0),total:Math.max(0,Number(q.subtotal)-Number(q.discount||0)),order:byQuote.get(Number(q.id))||null})),standaloneOrders:orders.rows.filter((o:any)=>!o.quote_id)});}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar tratativas'});}});
router.get('/quotes/:id',portalAuth,async(req,res)=>{try{const p=(req as any).portal,id=Number(req.params.id);const q=await pool.query(`SELECT q.*,COALESCE(SUM(i.quantity*i.unit_price),0)::float8 subtotal FROM quotes q LEFT JOIN quote_items i ON i.quote_id=q.id WHERE q.id=$1 AND q.account_id=$2 AND q.client_id=$3 AND q.status<>'draft' GROUP BY q.id`,[id,p.account_id,p.client_id]);if(!q.rows[0])return res.status(404).json({error:'Orçamento não encontrado'});const x=q.rows[0],items=await pool.query('SELECT description,item_type,quantity::float8 quantity,unit_price::float8 unit_price FROM quote_items WHERE quote_id=$1 ORDER BY sort_order,id',[id]);const o=x.order_id?await pool.query('SELECT id,type,status,date,priority,description,address FROM orders WHERE id=$1 AND account_id=$2 AND client_id=$3',[x.order_id,p.account_id,p.client_id]):{rows:[]};await event(p,'quote_viewed',id,x.order_id||undefined);res.json({id:Number(x.id),number:x.number,status:x.status,issueDate:x.issue_date,validUntil:x.valid_until,title:x.title,description:x.description,serviceAddress:x.service_address,discount:Number(x.discount||0),subtotal:Number(x.subtotal),total:Math.max(0,Number(x.subtotal)-Number(x.discount||0)),approvedAt:x.approved_at,items:items.rows.map((i:any)=>({description:i.description,itemType:i.item_type,quantity:Number(i.quantity),unitPrice:Number(i.unit_price)})),order:o.rows[0]||null});}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar orçamento'});}});
router.post('/quotes/:id/decision',portalAuth,async(req,res)=>{const db=await pool.connect();try{const p=(req as any).portal,id=Number(req.params.id),decision=String(req.body?.decision||'');if(!['approved','rejected'].includes(decision))return res.status(400).json({error:'Decisão inválida'});await db.query('BEGIN');const q=await db.query('SELECT id,status,order_id FROM quotes WHERE id=$1 AND account_id=$2 AND client_id=$3 FOR UPDATE',[id,p.account_id,p.client_id]);if(!q.rows[0]){await db.query('ROLLBACK');return res.status(404).json({error:'Orçamento não encontrado'});}if(q.rows[0].status!=='sent'){await db.query('ROLLBACK');return res.status(409).json({error:'Este orçamento já possui uma decisão ou foi convertido'});}await db.query(`UPDATE quotes SET status=$1,approved_at=CASE WHEN $1='approved' THEN NOW() ELSE approved_at END,updated_at=NOW() WHERE id=$2`,[decision,id]);await db.query('INSERT INTO client_portal_events(account_id,client_id,quote_id,event_type) VALUES($1,$2,$3,$4)',[p.account_id,p.client_id,id,decision==='approved'?'quote_approved':'quote_rejected']);await db.query('COMMIT');res.json({success:true,status:decision});}catch(e){try{await db.query('ROLLBACK')}catch{}console.error(e);res.status(500).json({error:'Erro ao registrar decisão'});}finally{db.release();}});
export default router;
