import { Router } from 'express';
import { pool } from '../db.js';
import { requireAdmin } from '../auth.js';
import { getAccountContext } from '../planLimits.js';

const router=Router();
async function accountId(userId:number){const ctx=await getAccountContext(userId);if(!ctx)throw new Error('Conta não encontrada');return ctx.accountId;}
const date=(v:any)=>v instanceof Date?v.toISOString().slice(0,10):String(v||'').slice(0,10);
const map=(p:any)=>({id:Number(p.id),clientId:p.client_id,clientName:p.client_name,name:p.name,description:p.description||'',intervalDays:Number(p.interval_days),firstScheduledDate:date(p.first_scheduled_date),nextScheduledDate:date(p.next_scheduled_date),active:Boolean(p.active),openOrderId:p.open_order_id||null});

router.get('/',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query(`SELECT p.*,c.name AS client_name,o.id AS open_order_id FROM preventive_maintenance_plans p JOIN clients c ON c.id=p.client_id AND c.account_id=p.account_id LEFT JOIN orders o ON o.account_id=p.account_id AND o.preventive_plan_id=p.id AND o.preventive_scheduled_date=p.next_scheduled_date WHERE p.account_id=$1 ORDER BY p.active DESC,p.next_scheduled_date,c.name`,[a]);res.json(r.rows.map(map));}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar manutenções preventivas'});}});
router.get('/radar',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query(`SELECT p.*,c.name AS client_name,o.id AS open_order_id FROM preventive_maintenance_plans p JOIN clients c ON c.id=p.client_id AND c.account_id=p.account_id LEFT JOIN orders o ON o.account_id=p.account_id AND o.preventive_plan_id=p.id AND o.preventive_scheduled_date=p.next_scheduled_date WHERE p.account_id=$1 AND p.active=TRUE AND p.next_scheduled_date<=CURRENT_DATE+30 ORDER BY p.next_scheduled_date,c.name`,[a]);const rows=r.rows.map(map);res.json({overdue:rows.filter((x:any)=>x.nextScheduledDate<date(new Date())),next7Days:rows.filter((x:any)=>x.nextScheduledDate>=date(new Date())&&new Date(x.nextScheduledDate+'T00:00:00').getTime()<=Date.now()+7*86400000),next30Days:rows.filter((x:any)=>x.nextScheduledDate>=date(new Date()))});}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar radar preventivo'});}});
router.get('/client/:clientId',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query(`SELECT p.*,c.name AS client_name,o.id AS open_order_id FROM preventive_maintenance_plans p JOIN clients c ON c.id=p.client_id AND c.account_id=p.account_id LEFT JOIN orders o ON o.account_id=p.account_id AND o.preventive_plan_id=p.id AND o.preventive_scheduled_date=p.next_scheduled_date WHERE p.account_id=$1 AND p.client_id=$2 ORDER BY p.active DESC,p.next_scheduled_date`,[a,req.params.clientId]);res.json(r.rows.map(map));}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar preventivas do cliente'});}});
router.post('/',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId),b=req.body||{},interval=Number(b.intervalDays);if(!b.clientId||!String(b.name||'').trim()||!/^\d{4}-\d{2}-\d{2}$/.test(String(b.firstScheduledDate||''))||!Number.isInteger(interval)||interval<=0)return res.status(400).json({error:'Cliente, nome, primeira data e intervalo positivo são obrigatórios'});const c=await pool.query('SELECT id FROM clients WHERE id=$1 AND account_id=$2',[b.clientId,a]);if(!c.rows[0])return res.status(400).json({error:'Cliente não pertence à conta'});const r=await pool.query(`INSERT INTO preventive_maintenance_plans(account_id,client_id,name,description,interval_days,first_scheduled_date,next_scheduled_date,active) VALUES($1,$2,$3,$4,$5,$6,$6,$7) RETURNING *`,[a,b.clientId,String(b.name).trim(),String(b.description||''),interval,b.firstScheduledDate,b.active!==false]);res.status(201).json(map(r.rows[0]));}catch(e){console.error(e);res.status(500).json({error:'Erro ao criar manutenção preventiva'});}});
router.post('/:id/create-order',requireAdmin,async(req,res)=>{const db=await pool.connect();try{const a=await accountId(req.userId),planId=Number(req.params.id);await db.query('BEGIN');const pr=await db.query(`SELECT p.*,c.name AS client_name,c.address,c.phone FROM preventive_maintenance_plans p JOIN clients c ON c.id=p.client_id AND c.account_id=p.account_id WHERE p.id=$1 AND p.account_id=$2 AND p.active=TRUE FOR UPDATE`,[planId,a]);const p=pr.rows[0];if(!p){await db.query('ROLLBACK');return res.status(404).json({error:'Plano preventivo ativo não encontrado'});}const scheduled=date(p.next_scheduled_date);const existing=await db.query('SELECT id FROM orders WHERE account_id=$1 AND preventive_plan_id=$2 AND preventive_scheduled_date=$3',[a,planId,scheduled]);if(existing.rows[0]){await db.query('ROLLBACK');return res.status(200).json({orderId:existing.rows[0].id,alreadyExists:true});}const now=new Date(),id=`OS-${String(now.getFullYear()).slice(2)}${String(now.getMonth()+1).padStart(2,'0')}-${Math.random().toString(36).slice(2,5).toUpperCase()}`;await db.query(`INSERT INTO orders(id,account_id,user_id,client_id,client_name,address,phone,type,status,date,priority,description,client_value,payment_status,preventive_plan_id,preventive_scheduled_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,'pending',$9,'medium',$10,0,'pending',$11,$9)`,[id,a,req.userId,p.client_id,p.client_name,p.address||'',p.phone||'',p.name,scheduled,p.description||'',planId]);await db.query('COMMIT');res.status(201).json({orderId:id,alreadyExists:false,scheduledDate:scheduled});}catch(e:any){try{await db.query('ROLLBACK');}catch{}if(e?.code==='23505')return res.status(409).json({error:'Já existe uma OS para esta ocorrência preventiva'});console.error(e);res.status(500).json({error:'Erro ao criar OS preventiva'});}finally{db.release();}});

router.put('/:id',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId),id=Number(req.params.id),b=req.body||{},interval=Number(b.intervalDays);if(!Number.isInteger(id)||id<=0||!String(b.name||'').trim()||!Number.isInteger(interval)||interval<=0)return res.status(400).json({error:'Dados inválidos'});const r=await pool.query(`UPDATE preventive_maintenance_plans SET name=$1,description=$2,interval_days=$3,active=$4,updated_at=NOW() WHERE id=$5 AND account_id=$6 RETURNING *`,[String(b.name).trim(),String(b.description||''),interval,b.active!==false,id,a]);if(!r.rows[0])return res.status(404).json({error:'Plano preventivo não encontrado'});res.json(map(r.rows[0]));}catch(e){console.error(e);res.status(500).json({error:'Erro ao atualizar manutenção preventiva'});}});
export default router;
