import { Router } from 'express';
import { pool } from '../db.js';
import { requireAdmin } from '../auth.js';
import { getAccountContext } from '../planLimits.js';

const router=Router();
async function accountId(userId:number){const ctx=await getAccountContext(userId);if(!ctx)throw new Error('Conta não encontrada');return ctx.accountId;}
const date=(v:any)=>v instanceof Date?v.toISOString().slice(0,10):String(v||'').slice(0,10);
const map=(p:any)=>({id:Number(p.id),clientId:p.client_id,clientName:p.client_name,name:p.name,description:p.description||'',intervalDays:Number(p.interval_days),firstScheduledDate:date(p.first_scheduled_date),nextScheduledDate:date(p.next_scheduled_date),active:Boolean(p.active),openOrderId:p.open_order_id||null});

router.get('/',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query(`SELECT p.*,c.name AS client_name,o.id AS open_order_id FROM preventive_maintenance_plans p JOIN clients c ON c.id=p.client_id AND c.account_id=p.account_id LEFT JOIN orders o ON o.account_id=p.account_id AND o.preventive_plan_id=p.id AND o.preventive_scheduled_date=p.next_scheduled_date WHERE p.account_id=$1 ORDER BY p.active DESC,p.next_scheduled_date,c.name`,[a]);res.json(r.rows.map(map));}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar manutenções preventivas'});}});
router.get('/radar',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query(`SELECT p.*,c.name AS client_name,o.id AS open_order_id FROM preventive_maintenance_plans p JOIN clients c ON c.id=p.client_id AND c.account_id=p.account_id LEFT JOIN orders o ON o.account_id=p.account_id AND o.preventive_plan_id=p.id AND o.preventive_scheduled_date=p.next_scheduled_date WHERE p.account_id=$1 AND p.active=TRUE AND p.next_scheduled_date<=CURRENT_DATE+30 ORDER BY p.next_scheduled_date,c.name`,[a]);const rows=r.rows.map(map);res.json({overdue:rows.filter((x:any)=>x.nextScheduledDate<date(new Date())),next7Days:rows.filter((x:any)=>x.nextScheduledDate>=date(new Date())&&new Date(x.nextScheduledDate+'T00:00:00').getTime()<=Date.now()+7*86400000),next30Days:rows.filter((x:any)=>x.nextScheduledDate>=date(new Date()))});}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar radar preventivo'});}});
router.get('/client/:clientId',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query(`SELECT p.*,c.name AS client_name,o.id AS open_order_id FROM preventive_maintenance_plans p JOIN clients c ON c.id=p.client_id AND c.account_id=p.account_id LEFT JOIN orders o ON o.account_id=p.account_id AND o.preventive_plan_id=p.id AND o.preventive_scheduled_date=p.next_scheduled_date WHERE p.account_id=$1 AND p.client_id=$2 ORDER BY p.active DESC,p.next_scheduled_date`,[a,req.params.clientId]);res.json(r.rows.map(map));}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar preventivas do cliente'});}});
router.post('/',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId),b=req.body||{},interval=Number(b.intervalDays);if(!b.clientId||!String(b.name||'').trim()||!/^\d{4}-\d{2}-\d{2}$/.test(String(b.firstScheduledDate||''))||!Number.isInteger(interval)||interval<=0)return res.status(400).json({error:'Cliente, nome, primeira data e intervalo positivo são obrigatórios'});const c=await pool.query('SELECT id FROM clients WHERE id=$1 AND account_id=$2',[b.clientId,a]);if(!c.rows[0])return res.status(400).json({error:'Cliente não pertence à conta'});const r=await pool.query(`INSERT INTO preventive_maintenance_plans(account_id,client_id,name,description,interval_days,first_scheduled_date,next_scheduled_date,active) VALUES($1,$2,$3,$4,$5,$6,$6,$7) RETURNING *`,[a,b.clientId,String(b.name).trim(),String(b.description||''),interval,b.firstScheduledDate,b.active!==false]);res.status(201).json(map(r.rows[0]));}catch(e){console.error(e);res.status(500).json({error:'Erro ao criar manutenção preventiva'});}});
router.put('/:id',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId),id=Number(req.params.id),b=req.body||{},interval=Number(b.intervalDays);if(!Number.isInteger(id)||id<=0||!String(b.name||'').trim()||!Number.isInteger(interval)||interval<=0)return res.status(400).json({error:'Dados inválidos'});const r=await pool.query(`UPDATE preventive_maintenance_plans SET name=$1,description=$2,interval_days=$3,active=$4,updated_at=NOW() WHERE id=$5 AND account_id=$6 RETURNING *`,[String(b.name).trim(),String(b.description||''),interval,b.active!==false,id,a]);if(!r.rows[0])return res.status(404).json({error:'Plano preventivo não encontrado'});res.json(map(r.rows[0]));}catch(e){console.error(e);res.status(500).json({error:'Erro ao atualizar manutenção preventiva'});}});
export default router;
