import { Router } from 'express';
import { pool } from '../db.js';
import { requireAdmin } from '../auth.js';
import { getAccountContext } from '../planLimits.js';

const router=Router();
async function accountId(userId:number){const ctx=await getAccountContext(userId);if(!ctx)throw new Error('Conta não encontrada');return ctx.accountId;}
const d=(v:any)=>v instanceof Date?v.toISOString().slice(0,10):v?String(v).slice(0,10):null;
const map=(q:any)=>({id:Number(q.id),number:q.number,clientId:q.client_id,clientName:q.client_name,status:q.status,issueDate:d(q.issue_date),validUntil:d(q.valid_until),title:q.title||'',description:q.description||'',discount:Number(q.discount||0),notes:q.notes||'',serviceAddress:q.service_address||'',orderId:q.order_id||null,subtotal:Number(q.subtotal||0),total:Math.max(0,Number(q.subtotal||0)-Number(q.discount||0)),items:Array.isArray(q.items)?q.items:[]});

async function nextNumber(db:any,a:number){const y=new Date().getFullYear();const r=await db.query(`SELECT number FROM quotes WHERE account_id=$1 AND number LIKE $2 ORDER BY id DESC LIMIT 1`,[a,`ORC-${y}-%`]);const last=Number(String(r.rows[0]?.number||'').split('-').pop())||0;return `ORC-${y}-${String(last+1).padStart(4,'0')}`;}
async function detail(a:number,id:number){const q=await pool.query(`SELECT q.*,c.name AS client_name,COALESCE(SUM(i.quantity*i.unit_price),0) subtotal FROM quotes q JOIN clients c ON c.id=q.client_id AND c.account_id=q.account_id LEFT JOIN quote_items i ON i.quote_id=q.id WHERE q.account_id=$1 AND q.id=$2 GROUP BY q.id,c.name`,[a,id]);if(!q.rows[0])return null;const items=await pool.query(`SELECT id,description,item_type AS "itemType",quantity::float8 AS quantity,unit_price::float8 AS "unitPrice" FROM quote_items WHERE quote_id=$1 ORDER BY sort_order,id`,[id]);return map({...q.rows[0],items:items.rows});}

router.get('/',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId);const r=await pool.query(`SELECT q.*,c.name AS client_name,COALESCE(SUM(i.quantity*i.unit_price),0) subtotal FROM quotes q JOIN clients c ON c.id=q.client_id AND c.account_id=q.account_id LEFT JOIN quote_items i ON i.quote_id=q.id WHERE q.account_id=$1 GROUP BY q.id,c.name ORDER BY q.created_at DESC`,[a]);res.json(r.rows.map(map));}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar orçamentos'});}});
router.get('/:id',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId),q=await detail(a,Number(req.params.id));if(!q)return res.status(404).json({error:'Orçamento não encontrado'});res.json(q);}catch(e){console.error(e);res.status(500).json({error:'Erro ao carregar orçamento'});}});

router.post('/',requireAdmin,async(req,res)=>{const db=await pool.connect();try{const a=await accountId(req.userId),b=req.body||{},items=Array.isArray(b.items)?b.items:[];if(!b.clientId||!String(b.title||'').trim()||!items.length)return res.status(400).json({error:'Cliente, título e ao menos um item são obrigatórios'});const c=await db.query('SELECT id FROM clients WHERE id=$1 AND account_id=$2',[b.clientId,a]);if(!c.rows[0])return res.status(400).json({error:'Cliente não pertence à conta'});await db.query('BEGIN');const number=await nextNumber(db,a);const q=await db.query(`INSERT INTO quotes(account_id,client_id,number,status,issue_date,valid_until,title,description,discount,notes,service_address) VALUES($1,$2,$3,'draft',COALESCE($4,CURRENT_DATE),$5,$6,$7,$8,$9,$10) RETURNING id`,[a,b.clientId,number,b.issueDate||null,b.validUntil||null,String(b.title).trim(),String(b.description||''),Math.max(0,Number(b.discount)||0),String(b.notes||''),String(b.serviceAddress||'')]);for(let i=0;i<items.length;i++){const x=items[i],qty=Number(x.quantity),price=Number(x.unitPrice);if(!String(x.description||'').trim()||!(qty>0)||price<0)throw new Error('ITEM_INVALID');await db.query(`INSERT INTO quote_items(quote_id,description,item_type,quantity,unit_price,sort_order) VALUES($1,$2,$3,$4,$5,$6)`,[q.rows[0].id,String(x.description).trim(),['service','material','other'].includes(x.itemType)?x.itemType:'service',qty,price,i]);}await db.query('COMMIT');res.status(201).json(await detail(a,q.rows[0].id));}catch(e:any){try{await db.query('ROLLBACK');}catch{}console.error(e);res.status(e?.message==='ITEM_INVALID'?400:500).json({error:e?.message==='ITEM_INVALID'?'Há itens inválidos no orçamento':'Erro ao criar orçamento'});}finally{db.release();}});

router.patch('/:id/status',requireAdmin,async(req,res)=>{try{const a=await accountId(req.userId),id=Number(req.params.id),status=String(req.body?.status||'');if(!['draft','sent','approved','rejected','expired'].includes(status))return res.status(400).json({error:'Status inválido'});const current=await pool.query('SELECT status,order_id FROM quotes WHERE id=$1 AND account_id=$2',[id,a]);if(!current.rows[0])return res.status(404).json({error:'Orçamento não encontrado'});if(current.rows[0].order_id||current.rows[0].status==='converted')return res.status(409).json({error:'Orçamento já convertido em OS'});if(current.rows[0].status==='approved'&&status!=='approved')return res.status(409).json({error:'Orçamento aprovado está congelado. Crie uma nova proposta para alterar a negociação.'});if(current.rows[0].status==='rejected'&&status!=='rejected')return res.status(409).json({error:'Orçamento recusado está encerrado. Crie uma nova proposta para retomar a negociação.'});const r=await pool.query(`UPDATE quotes SET status=$1,approved_at=CASE WHEN $1='approved' THEN COALESCE(approved_at,NOW()) ELSE approved_at END,updated_at=NOW() WHERE id=$2 AND account_id=$3 AND order_id IS NULL RETURNING id`,[status,id,a]);if(!r.rows[0])return res.status(409).json({error:'Orçamento não pode mais ser alterado'});res.json(await detail(a,id));}catch(e){console.error(e);res.status(500).json({error:'Erro ao atualizar orçamento'});}});

router.post('/:id/convert',requireAdmin,async(req,res)=>{const db=await pool.connect();try{const a=await accountId(req.userId),id=Number(req.params.id),b=req.body||{};await db.query('BEGIN');const locked=await db.query(`SELECT q.*,c.name client_name,c.address client_address,c.phone client_phone FROM quotes q JOIN clients c ON c.id=q.client_id AND c.account_id=q.account_id WHERE q.id=$1 AND q.account_id=$2 FOR UPDATE OF q`,[id,a]);const q=locked.rows[0];if(!q){await db.query('ROLLBACK');return res.status(404).json({error:'Orçamento não encontrado'});}if(q.order_id){await db.query('ROLLBACK');return res.json({orderId:q.order_id,alreadyExists:true});}if(q.status!=='approved'){await db.query('ROLLBACK');return res.status(409).json({error:'Apenas orçamentos aprovados podem gerar OS'});}const items=await db.query('SELECT description,quantity,unit_price FROM quote_items WHERE quote_id=$1 ORDER BY sort_order,id',[id]);const subtotal=items.rows.reduce((s:number,x:any)=>s+Number(x.quantity)*Number(x.unit_price),0),total=Math.max(0,subtotal-Number(q.discount||0));const now=new Date(),orderId=`OS-${String(now.getFullYear()).slice(2)}${String(now.getMonth()+1).padStart(2,'0')}-${Math.random().toString(36).slice(2,5).toUpperCase()}`;const description=String(b.description??[q.description,...items.rows.map((x:any)=>'• '+x.description)].filter(Boolean).join('\n'));const address=String(b.address??q.service_address??q.client_address??''),phone=String(b.phone??q.client_phone??''),type=String(b.type??q.title),date=String(b.date||new Date().toISOString().slice(0,10)),priority=String(b.priority||'medium'),serviceCategory=b.serviceCategory||null,materialSupply=String(b.materialSupply||'none'),clientValue=Number.isFinite(Number(b.clientValue))?Number(b.clientValue):total;await db.query(`INSERT INTO orders(id,account_id,user_id,client_id,client_name,address,phone,type,service_category,material_supply,status,date,priority,description,client_value,payment_status,quote_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'pending',$11,$12,$13,$14,'pending',$15)`,[orderId,a,req.userId,q.client_id,q.client_name,address,phone,type,serviceCategory,materialSupply,date,priority,description,clientValue,id]);if(Array.isArray(b.assignedTechnicianIds)){for(const technicianId of b.assignedTechnicianIds){await db.query('INSERT INTO order_technicians(order_id,technician_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[orderId,technicianId]);}}await db.query(`UPDATE quotes SET status='converted',order_id=$1,converted_at=NOW(),updated_at=NOW() WHERE id=$2 AND account_id=$3`,[orderId,id,a]);await db.query('COMMIT');res.status(201).json({orderId,alreadyExists:false});}catch(e:any){try{await db.query('ROLLBACK');}catch{}if(e?.code==='23505')return res.status(409).json({error:'Este orçamento já possui uma OS'});console.error(e);res.status(500).json({error:'Erro ao gerar OS do orçamento'});}finally{db.release();}});
export default router;
