export interface TrialInfo { planKey: string | null; startedAt: string | null; endsAt: string | null; status: 'not_started' | 'active' | 'expired' | 'ended'; active: boolean; daysRemaining: number; }
import type { ServiceOrder, Client, OrderStatus } from './types';
import type { AuthenticationResponseJSON, PublicKeyCredentialCreationOptionsJSON, PublicKeyCredentialRequestOptionsJSON, RegistrationResponseJSON } from '@simplewebauthn/browser';
import { cacheOrders, cacheUser, cacheClients, putClient, removeCachedClient, queueClientCreate, queueClientUpdate, queueClientDelete, cacheTeam, getCachedTeam, getQueue, removeQueueItem, queueOrderCreate, queueOrderUpdate, queueOrderDelete, queueAttendancePhoto, queueSignatureUpload, removeCachedOrder, getOfflineSnapshot, cacheSnapshot, type OfflineSnapshot } from './offlineStore';
const BASE='/api';
export async function checkServerHealth():Promise<{ok:boolean}> { const res=await fetch(`${BASE}/health`,{method:'GET',credentials:'include',cache:'no-store'}); if(!res.ok) throw new Error(`Servidor respondeu HTTP ${res.status}`); const body=await res.json().catch(()=>null); if(!body?.ok) throw new Error('Resposta de saúde do servidor inválida'); return {ok:true}; }
function getCsrfToken(){const m=document.cookie.match(/(?:^|; )qtecnico_csrf=([^;]+)/);return m?decodeURIComponent(m[1]):null;}
async function request<T>(path: string, options: RequestInit = {}): Promise<T> {
  const method = (options.method || 'GET').toUpperCase();
  const headers: Record<string, string> = { 'Content-Type': 'application/json', ...(options.headers as Record<string, string> || {}) };
  if (['POST', 'PUT', 'PATCH', 'DELETE'].includes(method)) {
    const csrf = getCsrfToken();
    if (csrf) headers['X-CSRF-Token'] = csrf;
  }
  const controller = new AbortController();
  const timeout = window.setTimeout(() => controller.abort(), 30000);
  try {
    const res = await fetch(`${BASE}${path}`, { ...options, credentials: 'include', headers, signal: controller.signal });
    if (res.status === 401) window.dispatchEvent(new CustomEvent('qtecnico-session-expired'));
    const contentType = res.headers.get('content-type') || '';
    const text = await res.text();
    let body: unknown;
    let parsed = false;
    if (text && contentType.toLowerCase().includes('application/json')) {
      try {
        body = JSON.parse(text);
        parsed = true;
      } catch { /* Report malformed JSON with the same safe HTTP diagnostics. */ }
    }
    // JSON null is a valid response for accounts without a company profile.
    // Never include raw response text: it can contain personal data or server details.
    if (!parsed) {
      throw Object.assign(new Error(`A API retornou uma resposta inválida (HTTP ${res.status}; ${BASE}${path}; Content-Type: ${contentType || 'ausente'})`), {
        status: res.status, path: `${BASE}${path}`, contentType,
      });
    }
    if (!res.ok) {
      const message = body && typeof body === 'object' && 'error' in body && typeof body.error === 'string'
        ? body.error : 'Erro na requisição';
      throw Object.assign(new Error(message), { status: res.status, body, path: `${BASE}${path}`, contentType });
    }
    return body as T;
  } catch (error) {
    if (error instanceof DOMException && error.name === 'AbortError') throw new Error(`Tempo limite excedido ao comunicar com ${path}`);
    throw error;
  } finally {
    window.clearTimeout(timeout);
  }
}
async function uploadFile<T>(file:File,folder:'attendances'|'signatures'|'profiles'='attendances'):Promise<T>{const form=new FormData();form.append('file',file);form.append('folder',folder);const headers:Record<string,string>={};const csrf=getCsrfToken();if(csrf)headers['X-CSRF-Token']=csrf;const res=await fetch(`${BASE}/uploads`,{method:'POST',body:form,credentials:'include',headers});if(res.status===401)window.dispatchEvent(new CustomEvent('qtecnico-session-expired'));const body=await res.json().catch(()=>null);if(!res.ok)throw new Error(body?.error||'Erro ao enviar imagem');return body as T;}
function notifyAuthenticated(){window.dispatchEvent(new CustomEvent('qtecnico-authenticated'));}
function normalizeOrder(order:any):ServiceOrder{const status:OrderStatus=order?.status==='in_progress'||order?.status==='completed'||order?.status==='cancelled'||order?.status==='pending'?order.status:'pending';return{...order,syncVersion:Number.isFinite(Number(order?.syncVersion))?Number(order.syncVersion):undefined,status,clientId:String(order?.clientId??''),client:String(order?.client??''),address:String(order?.address??''),phone:String(order?.phone??''),type:String(order?.type??''),date:String(order?.date??''),priority:order?.priority==='low'||order?.priority==='high'?'low'===order.priority?'low':'high':'medium',description:String(order?.description??''),clientValue:Number(order?.clientValue??0),expenses:Array.isArray(order?.expenses)?order.expenses:[],attendances:Array.isArray(order?.attendances)?order.attendances.map((a:any)=>({...a,photos:Array.isArray(a?.photos)?a.photos:[]})):[],payments:Array.isArray(order?.payments)?order.payments:[],paymentStatus:order?.paymentStatus==='paid'?'paid':'pending',assignedTechnicians:Array.isArray(order?.assignedTechnicians)?order.assignedTechnicians:[],assignedTechnicianIds:Array.isArray(order?.assignedTechnicianIds)?order.assignedTechnicianIds:[],assignedTechnicianId:order?.assignedTechnicianId??null,assignedTechnicianName:order?.assignedTechnicianName??null};}
function finiteNumber(value:any,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function normalizeDashboardSummary(summary:any):DashboardSummary{const rawStats=summary?.stats??{};const nullableNumber=(value:any)=>value==null?null:finiteNumber(value);return{period:String(summary?.period??''),planKey:String(summary?.planKey??'essential'),entitlements:{basicFinancial:Boolean(summary?.entitlements?.basicFinancial),advancedFinancial:Boolean(summary?.entitlements?.advancedFinancial)},stats:{total:finiteNumber(rawStats.total),pending:finiteNumber(rawStats.pending),inProgress:finiteNumber(rawStats.inProgress),completed:finiteNumber(rawStats.completed),cancelled:finiteNumber(rawStats.cancelled),today:finiteNumber(rawStats.today),revenue:nullableNumber(rawStats.revenue),paid:nullableNumber(rawStats.paid),receivable:nullableNumber(rawStats.receivable),averageTicket:nullableNumber(rawStats.averageTicket),costs:nullableNumber(rawStats.costs),margin:nullableNumber(rawStats.margin),clients:finiteNumber(rawStats.clients),newClients:finiteNumber(rawStats.newClients)},monthly:Array.isArray(summary?.monthly)?summary.monthly.map((m:any)=>({month:String(m?.month??''),revenue:nullableNumber(m?.revenue),orders:finiteNumber(m?.orders)})):[],technicians:Array.isArray(summary?.technicians)?summary.technicians.map((t:any)=>({id:finiteNumber(t?.id),name:String(t?.name??'Técnico'),orders:finiteNumber(t?.orders),completed:finiteNumber(t?.completed),revenue:nullableNumber(t?.revenue)})):[],recent:Array.isArray(summary?.recent)?summary.recent.map((o:any)=>{const normalized=normalizeOrder({...o,clientValue:o?.value??0});return{id:String(normalized.id??''),client:normalized.client,type:normalized.type,status:normalized.status,date:normalized.date,value:nullableNumber(o?.value),technician:o?.technician==null?null:String(o.technician)}}):[]};}
export interface PlanAccess{contractedPlanKey:string;trial:TrialInfo;allowed:boolean;planKey:string;features:string[];limits:Record<string,any>;}
export interface UserProfile{id:number;accountId:number|null;name:string;role:string;phone:string;email:string;isAdmin?:boolean;photoUrl?:string|null;}
export interface TeamMember{id:number;name:string;role:string;phone:string;email:string;isAdmin:boolean;createdAt?:string;}
export interface CompanyProfileData{id:number;legalName:string;tradeName:string;document:string;phone:string;whatsapp:string;email:string;website:string;postalCode:string;address:string;number:string;complement:string;neighborhood:string;city:string;state:string;logoKey:string;description:string;updatedAt?:string;logoUrl?:string|null;}
export interface DashboardSummary{period:string;planKey:string;entitlements:{basicFinancial:boolean;advancedFinancial:boolean};stats:{total:number;pending:number;inProgress:number;completed:number;cancelled:number;today:number;revenue:number|null;paid:number|null;receivable:number|null;averageTicket:number|null;costs:number|null;margin:number|null;clients:number;newClients:number};monthly:{month:string;revenue:number|null;orders:number}[];technicians:{id:number;name:string;orders:number;completed:number;revenue:number|null}[];recent:{id:string;client:string;type:string;status:OrderStatus;date:string;value:number|null;technician:string|null}[];}
export interface BillingPlan{id:number;key:string;name:string;description:string;amount:number;currency:string;billingInterval:string;active:boolean;features:string[];limits:Record<string,any>;}
export interface BillingPayment{id:number;amount:number;currency:string;status:string;dueAt:string|null;paidAt:string|null;refundedAt:string|null;provider:string|null;providerPaymentId:string|null;invoiceUrl:string|null;failureReason:string|null;createdAt:string;}
export interface BillingSubscription{id:number;planKey:string;planName:string;status:string;amount:number;currency:string;billingInterval:string;trialStartAt:string|null;trialEndAt:string|null;currentPeriodStart:string|null;currentPeriodEnd:string|null;canceledAt:string|null;provider:string|null;providerSubscriptionId:string|null;}
export interface BillingData{account:{id:number;planKey?:string;subscriptionStatus?:string;currentPeriodEnd?:string|null;company?:string;email?:string;document?:string;};subscription:BillingSubscription|null;plans:BillingPlan[];payments:BillingPayment[];}
type AuthResponse={user:UserProfile;token?:never};
const fileToDataUrl=(file:Blob):Promise<string>=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||''));reader.onerror=()=>reject(reader.error||new Error('Não foi possível armazenar a imagem localmente.'));reader.readAsDataURL(file);});
const isOfflineFailure=(error:unknown)=>!navigator.onLine||error instanceof TypeError||((error as any)?.name==='AbortError');
const localOrderId=()=>{const now=new Date();const prefix=`OS-${String(now.getFullYear()).slice(2)}${String(now.getMonth()+1).padStart(2,'0')}`;return `${prefix}-${Math.random().toString(36).slice(2,5).toUpperCase()}`;};
export const api={
 login:async(email:string,password:string)=>{const result=await request<AuthResponse>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});await cacheUser(result.user);notifyAuthenticated();return result;},
 register:async(name:string,email:string,password:string)=>{const result=await request<AuthResponse>('/auth/register',{method:'POST',body:JSON.stringify({name,email,password})});await cacheUser(result.user);notifyAuthenticated();return result;},
 logout:()=>request<{success:boolean}>('/auth/logout',{method:'POST'}),requestPasswordReset:(email:string)=>request<{message:string}>('/auth/password-reset/request',{method:'POST',body:JSON.stringify({email})}),resetPassword:(email:string,code:string,password:string)=>request<{success:boolean}>('/auth/password-reset/confirm',{method:'POST',body:JSON.stringify({email,code,password})}),
 webauthnRegisterOptions:()=>request<PublicKeyCredentialCreationOptionsJSON>('/auth/webauthn/register/options',{method:'POST'}),webauthnRegisterVerify:(response:RegistrationResponseJSON)=>request<{success:boolean}>('/auth/webauthn/register/verify',{method:'POST',body:JSON.stringify(response)}),webauthnAuthenticationOptions:(email?:string)=>request<PublicKeyCredentialRequestOptionsJSON>('/auth/webauthn/authenticate/options',{method:'POST',body:JSON.stringify(email?.trim()?{email:email.trim()}: {})}),webauthnAuthenticationVerify:async(response:AuthenticationResponseJSON)=>{const result=await request<AuthResponse>('/auth/webauthn/authenticate/verify',{method:'POST',body:JSON.stringify(response)});await cacheUser(result.user);notifyAuthenticated();return result;},
 getMe:async()=>{try{const user=await request<UserProfile>('/users/me');await cacheUser(user);return user;}catch(error){if(isOfflineFailure(error)){const cached=await getOfflineSnapshot();if(cached.user)return cached.user;}throw error;}},getAdminAccess:()=>request<PlanAccess>('/users/admin/access'),getDashboardSummary:async(days:string='30')=>{try{return normalizeDashboardSummary(await request<unknown>(`/dashboard/summary?days=${encodeURIComponent(days)}`));}catch(error){if(isOfflineFailure(error)){const snapshot=await getOfflineSnapshot();const orders=snapshot.orders;const total=orders.length;const pending=orders.filter(o=>o.status==='pending').length;const inProgress=orders.filter(o=>o.status==='in_progress').length;const completed=orders.filter(o=>o.status==='completed').length;const cancelled=orders.filter(o=>o.status==='cancelled').length;const revenue=orders.reduce((sum,o)=>sum+finiteNumber(o.clientValue),0);const paid=orders.reduce((sum,o)=>sum+finiteNumber(o.paymentStatus==='paid'?o.clientValue:0),0);const costs=orders.reduce((sum,o)=>sum+o.expenses.reduce((s,e)=>s+finiteNumber(e.amount),0),0);const clients=new Set(orders.map(o=>String(o.clientId||o.client||'')).filter(Boolean)).size;return normalizeDashboardSummary({period:days,stats:{total,pending,inProgress,completed,cancelled,revenue,paid,costs,margin:revenue-costs,clients,newClients:0},monthly:[],technicians:[],recent:orders.slice(0,10).map(o=>({id:o.id,client:o.client,type:o.type,status:o.status,date:o.date,value:o.clientValue,technician:o.assignedTechnicianName||null}))});}throw error;}},getTeam:async()=>{try{const team=await request<TeamMember[]>('/users/admin/team');await cacheTeam(team);return team;}catch(error){if(isOfflineFailure(error)){const cached=await getCachedTeam();if(cached.length)return cached;}throw error;}},createTeamMember:(data:{name:string;email:string;password:string;phone:string;role:string})=>request<TeamMember>('/users/admin/team',{method:'POST',body:JSON.stringify(data)}),deleteTeamMember:(id:number)=>request<{success:boolean}>(`/users/admin/team/${id}`,{method:'DELETE'}),updateProfile:(data:Partial<Omit<UserProfile,'id'>>&{name:string;email:string;photoKey?:string})=>request<UserProfile>('/users/me',{method:'PUT',body:JSON.stringify(data)}),getCompanyProfile:()=>request<CompanyProfileData|null>('/users/admin/company-profile'),getDocumentCompanyProfile:()=>request<CompanyProfileData|null>('/users/company-profile'),updateCompanyProfile:(data:CompanyProfileData)=>request<CompanyProfileData>('/users/admin/company-profile',{method:'PUT',body:JSON.stringify(data)}),
  getTrial:()=>request<{trial:TrialInfo;contractedPlanKey:string;effectivePlanKey:string}>('/users/trial'),
  getBilling:()=>request<BillingData>('/dashboard/billing'),
  subscribeBilling:(planKey:string,billingType:'PIX'|'CREDIT_CARD'|'BOLETO')=>request<{success:boolean;subscriptionId:number;providerSubscriptionId:string;payments:{id:string;status:string;invoiceUrl:string|null;dueDate:string|null;value:number;billingType:string}[]}>('/dashboard/billing/subscribe',{method:'POST',body:JSON.stringify({planKey,billingType})}),
  refreshBilling:()=>request<{payments:any[]}>('/dashboard/billing/refresh',{method:'POST'}),
  uploadPhoto:(file:File,folder:'attendances'|'signatures'|'profiles'='attendances')=>uploadFile<{key:string;url:string}>(file,folder),
  addAttendancePhoto:async(orderId:string,attendanceId:string,file:File)=>{const normalizedOrderId=String(orderId);const normalizedAttId=String(attendanceId);const queueLocally=async()=>{const snapshot=await getOfflineSnapshot();const order=snapshot.orders.find(o=>String(o.id)===normalizedOrderId);if(!order)throw new Error('Esta OS ainda não está disponível offline. Abra a OS com internet antes de trabalhar offline.');const photoId=`local-photo-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const dataUrl=await fileToDataUrl(file);const next=normalizeOrder({...order,attendances:(order.attendances||[]).map(a=>String(a.id)===normalizedAttId?{...a,photos:[...(a.photos||[]),{id:photoId,key:'',dataUrl,name:file.name}]}:a)});await queueAttendancePhoto(next,normalizedAttId,photoId,file,file.name);return{photo:{id:photoId,key:'',dataUrl,name:file.name}};};const queue=await getQueue();const isPendingCreate=queue.some(q=>q.type==='order_create'&&String(q.orderId)===normalizedOrderId);if(!navigator.onLine||isPendingCreate){return await queueLocally();}try{const {key,url}=await uploadFile<{key:string;url:string}>(file,'attendances');return await request<{photo:{id:string;key:string;dataUrl:string;name:string}}>(`/orders/${encodeURIComponent(normalizedOrderId)}/attendances/${encodeURIComponent(normalizedAttId)}/photos`,{method:'POST',body:JSON.stringify({key,url,name:file.name})});}catch(error){if(isOfflineFailure(error)){return await queueLocally();}throw error;}},
 registerAttendancePhoto:(orderId:string,attendanceId:string,data:{id?:string;key:string;url:string;name:string})=>request<{photo:{id:string;key:string;dataUrl:string;name:string}}>(`/orders/${encodeURIComponent(orderId)}/attendances/${encodeURIComponent(attendanceId)}/photos`,{method:'POST',body:JSON.stringify(data)}),
  deleteAttendancePhoto:async(orderId:string,attendanceId:string,photoId:string):Promise<{success:boolean;order?:ServiceOrder;pending?:boolean}>=>{const normalizedOrderId=String(orderId);const normalizedAttId=String(attendanceId);const normalizedPhotoId=String(photoId);const removeLocally=async()=>{const snapshot=await getOfflineSnapshot();const order=snapshot.orders.find(o=>String(o.id)===normalizedOrderId);const queue=await getQueue();for(const item of queue){if(item.type==='attendance_photo'&&String(item.orderId)===normalizedOrderId&&String(item.photoId)===normalizedPhotoId){await removeQueueItem(item.id);}}if(order){const next=normalizeOrder({...order,attendances:(order.attendances||[]).map(a=>String(a.id)===normalizedAttId?{...a,photos:(a.photos||[]).filter(p=>String(p.id)!==normalizedPhotoId)}:a)});await queueOrderUpdate(next);return{success:true,order:next,pending:true};}return{success:true,pending:true};};if(!navigator.onLine||normalizedPhotoId.startsWith('local-photo-')){return await removeLocally();}try{const result=await request<{success:boolean}>(`/orders/${encodeURIComponent(normalizedOrderId)}/attendances/${encodeURIComponent(normalizedAttId)}/photos/${encodeURIComponent(normalizedPhotoId)}`,{method:'DELETE'});return result;}catch(error){if(isOfflineFailure(error)||(error as any)?.status===404){return await removeLocally();}throw error;}},
  saveSignature:async(order:ServiceOrder,file:File):Promise<{order:ServiceOrder;pending:boolean}>=>{const queueLocally=async()=>{const dataUrl=await fileToDataUrl(file);const next=normalizeOrder({...order,clientSignature:dataUrl,clientSignatureKey:`local-signature-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,status:'completed'});await queueSignatureUpload(next,file,file.name);return{order:next,pending:true};};const queue=await getQueue();const isPendingCreate=queue.some(q=>q.type==='order_create'&&String(q.orderId)===String(order.id));if(!navigator.onLine||isPendingCreate){return await queueLocally();}try{const {key,url}=await uploadFile<{key:string;url:string}>(file,'signatures');const saved=await api.updateOrderOnline(order.id,{clientSignature:url,clientSignatureKey:key,status:'completed'});await cacheOrders([saved]);return{order:saved,pending:false};}catch(error){if(isOfflineFailure(error)){return await queueLocally();}throw error;}},
  getOrders:async()=>{try{const rawOrders=await request<unknown>('/orders');const orders=Array.isArray(rawOrders)?rawOrders.map(normalizeOrder):[];try{const snapshot=await getOfflineSnapshot();if(snapshot.user)await cacheSnapshot(orders,snapshot.user);}catch(cacheError){console.warn('Não foi possível atualizar o cache offline de OS:',cacheError);}const queue=await getQueue();const pendingDeletes=new Set(queue.filter(q=>q.type==='order_delete').map(q=>String(q.orderId)));const pendingUpdates=new Map(queue.filter(q=>q.type==='order_update'&&q.order).map(q=>[String(q.orderId),q.order as ServiceOrder]));const pendingCreates=queue.filter(q=>q.type==='order_create'&&q.order).map(q=>q.order as ServiceOrder);const merged=orders.filter(o=>!pendingDeletes.has(String(o.id))).map(o=>pendingUpdates.get(String(o.id))||o);for(const c of pendingCreates){if(!pendingDeletes.has(String(c.id))&&!merged.some(o=>String(o.id)===String(c.id))){merged.unshift(c);}}return merged;}catch(error){if(isOfflineFailure(error)){const cached=await getOfflineSnapshot();return cached.orders.map(normalizeOrder);}throw error;}},
 createOrderOnline:(order:ServiceOrder)=>request<ServiceOrder>('/orders',{method:'POST',body:JSON.stringify(normalizeOrder(order))}),
 createOrder:async(order:ServiceOrder):Promise<ServiceOrder>=>{const normalized=normalizeOrder(order);if(!navigator.onLine){const local=normalizeOrder({...normalized,id:normalized.id||localOrderId()});await queueOrderCreate(local);return local;}try{const saved=normalizeOrder(await api.createOrderOnline(normalized));await cacheOrders([saved]);return saved;}catch(error){if(isOfflineFailure(error)){const local=normalizeOrder({...normalized,id:normalized.id||localOrderId()});await queueOrderCreate(local);return local;}throw error;}},
 updateOrderOnline:(id:string,order:Partial<ServiceOrder>)=>request<ServiceOrder>(`/orders/${id}`,{method:'PUT',body:JSON.stringify(order)}),
  syncOrderOnline:(id:string,order:Partial<ServiceOrder>,operationId:string,baseVersion?:number)=>request<ServiceOrder>(`/orders/${id}/sync`,{method:'PUT',body:JSON.stringify({...order,operationId,baseVersion})}),
  updateOrder:async(id:string,order:Partial<ServiceOrder>,fallback?:ServiceOrder):Promise<ServiceOrder>=>{const normalizedId=String(id);const getBase=(snap:OfflineSnapshot)=>fallback||snap.orders.find(o=>String(o.id)===normalizedId)||({id:normalizedId,client:'',address:'',phone:'',type:'',date:'',priority:'medium',description:'',status:'pending',clientValue:0,expenses:[],attendances:[],payments:[],paymentStatus:'pending',assignedTechnicians:[],assignedTechnicianIds:[]} as ServiceOrder);const queue=await getQueue();const isPendingCreate=queue.some(q=>q.type==='order_create'&&String(q.orderId)===normalizedId);if(!navigator.onLine||isPendingCreate){const snapshot=await getOfflineSnapshot();const next=normalizeOrder({...getBase(snapshot),...order,id:normalizedId});await queueOrderUpdate(next);return next;}try{const saved=normalizeOrder(await api.updateOrderOnline(normalizedId,order));await cacheOrders([saved]);return saved;}catch(error){if(isOfflineFailure(error)){const snapshot=await getOfflineSnapshot();const next=normalizeOrder({...getBase(snapshot),...order,id:normalizedId});await queueOrderUpdate(next);return next;}throw error;}},
 updateOrderOffline:async(id:string,order:Partial<ServiceOrder>,fallback:ServiceOrder):Promise<{order:ServiceOrder;pending:boolean}>=>{const next=normalizeOrder({...fallback,...order});if(!navigator.onLine){await queueOrderUpdate(next);return{order:next,pending:true};}try{const saved=normalizeOrder(await api.updateOrderOnline(id,order));await cacheOrders([saved]);return{order:saved,pending:false};}catch(error){if(isOfflineFailure(error)){await queueOrderUpdate(next);return{order:next,pending:true};}throw error;}},
 deleteOrderOnline:async(id:string)=>request<{success:boolean}>(`/orders/${id}`,{method:'DELETE'}),
 deleteOrder:async(id:string,fallback?:ServiceOrder):Promise<{success:boolean;pending?:boolean}>=>{const normalizedId=String(id);if(!navigator.onLine){await queueOrderDelete(normalizedId,fallback);return{success:true,pending:true};}try{const result=await api.deleteOrderOnline(normalizedId);await removeCachedOrder(normalizedId);return{...result,pending:false};}catch(error){if(isOfflineFailure(error)){await queueOrderDelete(normalizedId,fallback);return{success:true,pending:true};}throw error;}},
  getClients:async()=>{try{const rawClients=await request<Client[]>('/clients');const clients=Array.isArray(rawClients)?rawClients:[];await cacheClients(clients);const queue=await getQueue();const pendingDeletes=new Set(queue.filter(q=>q.type==='client_delete'&&q.clientId).map(q=>String(q.clientId)));const pendingUpdates=new Map(queue.filter(q=>q.type==='client_update'&&q.client&&q.clientId).map(q=>[String(q.clientId),q.client as Client]));const pendingCreates=queue.filter(q=>q.type==='client_create'&&q.client).map(q=>q.client as Client);const merged=clients.filter(c=>!pendingDeletes.has(String(c.id))).map(c=>pendingUpdates.get(String(c.id))||c);for(const c of pendingCreates){if(!pendingDeletes.has(String(c.id))&&!merged.some(x=>String(x.id)===String(c.id))){merged.push(c);}}return merged;}catch(error){if(isOfflineFailure(error)){const cached=await getOfflineSnapshot();return cached.clients;}throw error;}},
 createClientOnline:(client:Client)=>request<Client>('/clients',{method:'POST',body:JSON.stringify(client)}),
 createClient:async(client:Client):Promise<Client>=>{const newClient:Client={...client,id:client.id||Date.now().toString()};if(!navigator.onLine){await queueClientCreate(newClient);return newClient;}try{const created=await api.createClientOnline(newClient);await putClient(created);return created;}catch(error){if(isOfflineFailure(error)){await queueClientCreate(newClient);return newClient;}throw error;}},
 updateClientOnline:(id:string,client:Partial<Client>)=>request<Client>(`/clients/${id}`,{method:'PUT',body:JSON.stringify(client)}),
  updateClient:async(id:string,client:Partial<Client>):Promise<Client>=>{const normalizedId=String(id);const queue=await getQueue();const isPendingCreate=queue.some(q=>q.type==='client_create'&&String(q.clientId)===normalizedId);const fallbackClient:Client={id:normalizedId,name:'',document:'',address:'',phone:'',email:''};if(!navigator.onLine||isPendingCreate){const snapshot=await getOfflineSnapshot();const existing=snapshot.clients.find(c=>String(c.id)===normalizedId);const updated:Client={...fallbackClient,...existing,...client,id:normalizedId};await queueClientUpdate(updated);return updated;}try{const updated=await api.updateClientOnline(normalizedId,client);await putClient(updated);return updated;}catch(error){if(isOfflineFailure(error)){const snapshot=await getOfflineSnapshot();const existing=snapshot.clients.find(c=>String(c.id)===normalizedId);const updated:Client={...fallbackClient,...existing,...client,id:normalizedId};await queueClientUpdate(updated);return updated;}throw error;}},
 deleteClientOnline:(id:string)=>request<{success:boolean}>(`/clients/${id}`,{method:'DELETE'}),
  deleteClient:async(id:string):Promise<{success:boolean;pending?:boolean}>=>{const normalizedId=String(id);if(!navigator.onLine){await queueClientDelete(normalizedId);return{success:true,pending:true};}try{const result=await api.deleteClientOnline(normalizedId);await removeCachedClient(normalizedId);return{...result,pending:false};}catch(error){if(isOfflineFailure(error)){await queueClientDelete(normalizedId);return{success:true,pending:true};}throw error;}}
};
