import type { ServiceOrder, Client, OrderStatus } from './types';
import type { AuthenticationResponseJSON, PublicKeyCredentialCreationOptionsJSON, PublicKeyCredentialRequestOptionsJSON, RegistrationResponseJSON } from '@simplewebauthn/browser';
const BASE='/api';
function getCsrfToken(){const m=document.cookie.match(/(?:^|; )qtecnico_csrf=([^;]+)/);return m?decodeURIComponent(m[1]):null;}
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const method=(options.method||'GET').toUpperCase();const headers:Record<string,string>={'Content-Type':'application/json',...(options.headers as Record<string,string>||{})};if(['POST','PUT','PATCH','DELETE'].includes(method)){const csrf=getCsrfToken();if(csrf)headers['X-CSRF-Token']=csrf;}const res=await fetch(`${BASE}${path}`,{...options,credentials:'include',headers});if(res.status===401)window.dispatchEvent(new CustomEvent('qtecnico-session-expired'));const contentType=res.headers.get('content-type')||'';const text=await res.text();let body:any=null;if(text&&contentType.includes('application/json'))body=JSON.parse(text);if(!res.ok)throw new Error(body?.error||(contentType.includes('text/html')?'O servidor retornou uma página HTML em vez de uma resposta da API':'Erro na requisição'));if(!body)throw new Error('A API retornou uma resposta inválida');return body as T;}
function uploadFile<T>(file:File,folder:'attendances'|'signatures'|'profiles'='attendances'):Promise<T>{const form=new FormData();form.append('file',file);form.append('folder',folder);const headers:Record<string,string>={};const csrf=getCsrfToken();if(csrf)headers['X-CSRF-Token']=csrf;return fetch(`${BASE}/uploads`,{method:'POST',body:form,credentials:'include',headers}).then(async res=>{if(res.status===401)window.dispatchEvent(new CustomEvent('qtecnico-session-expired'));const body=await res.json().catch(()=>null);if(!res.ok)throw new Error(body?.error||'Erro ao enviar imagem');return body as T;});}
function notifyAuthenticated(){window.dispatchEvent(new CustomEvent('qtecnico-authenticated'));}
function normalizeOrder(order:any):ServiceOrder{const status:OrderStatus=order?.status==='in_progress'||order?.status==='completed'||order?.status==='cancelled'||order?.status==='pending'?order.status:'pending';return{...order,status,clientId:String(order?.clientId??''),client:String(order?.client??''),address:String(order?.address??''),phone:String(order?.phone??''),type:String(order?.type??''),date:String(order?.date??''),priority:order?.priority==='low'||order?.priority==='high'?'low'===order.priority?'low':'high':'medium',description:String(order?.description??''),clientValue:Number(order?.clientValue??0),expenses:Array.isArray(order?.expenses)?order.expenses:[],attendances:Array.isArray(order?.attendances)?order.attendances.map((a:any)=>({...a,photos:Array.isArray(a?.photos)?a.photos:[]})):[],payments:Array.isArray(order?.payments)?order.payments:[],paymentStatus:order?.paymentStatus==='paid'?'paid':'pending',assignedTechnicians:Array.isArray(order?.assignedTechnicians)?order.assignedTechnicians:[],assignedTechnicianIds:Array.isArray(order?.assignedTechnicianIds)?order.assignedTechnicianIds:[],assignedTechnicianId:order?.assignedTechnicianId??null,assignedTechnicianName:order?.assignedTechnicianName??null};}
function finiteNumber(value:any,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function normalizeDashboardSummary(summary:any):DashboardSummary{const rawStats=summary?.stats??{};return{period:String(summary?.period??''),stats:{total:finiteNumber(rawStats.total),pending:finiteNumber(rawStats.pending),inProgress:finiteNumber(rawStats.inProgress),completed:finiteNumber(rawStats.completed),cancelled:finiteNumber(rawStats.cancelled),revenue:finiteNumber(rawStats.revenue),paid:finiteNumber(rawStats.paid),costs:finiteNumber(rawStats.costs),margin:finiteNumber(rawStats.margin),clients:finiteNumber(rawStats.clients),newClients:finiteNumber(rawStats.newClients)},monthly:Array.isArray(summary?.monthly)?summary.monthly.map((m:any)=>({month:String(m?.month??''),revenue:finiteNumber(m?.revenue),orders:finiteNumber(m?.orders)})):[],technicians:Array.isArray(summary?.technicians)?summary.technicians.map((t:any)=>({id:finiteNumber(t?.id),name:String(t?.name??'Técnico'),orders:finiteNumber(t?.orders),completed:finiteNumber(t?.completed),revenue:finiteNumber(t?.revenue)})):[],recent:Array.isArray(summary?.recent)?summary.recent.map((o:any)=>{const normalized=normalizeOrder({...o,clientValue:o?.value??0});return{id:String(normalized.id??''),client:normalized.client,type:normalized.type,status:normalized.status,date:normalized.date,value:finiteNumber(o?.value),technician:o?.technician==null?null:String(o.technician)}}):[]};}
export interface UserProfile{id:number;name:string;role:string;phone:string;email:string;isAdmin?:boolean;photoUrl?:string|null;}
export interface TeamMember{id:number;name:string;role:string;phone:string;email:string;isAdmin:boolean;createdAt?:string;}
export interface CompanyProfileData{id:number;legalName:string;tradeName:string;document:string;phone:string;whatsapp:string;email:string;website:string;postalCode:string;address:string;number:string;complement:string;neighborhood:string;city:string;state:string;logoKey:string;description:string;updatedAt?:string;}
export interface DashboardSummary{period:string;stats:{total:number;pending:number;inProgress:number;completed:number;cancelled:number;revenue:number;paid:number;costs:number;margin:number;clients:number;newClients:number};monthly:{month:string;revenue:number;orders:number}[];technicians:{id:number;name:string;orders:number;completed:number;revenue:number}[];recent:{id:string;client:string;type:string;status:OrderStatus;date:string;value:number;technician:string|null}[];}
export interface BillingPlan{key:string;name:string;description:string|null;amount:number;currency:string;billingInterval:string;features:any;limits:any;}
export interface BillingPayment{id:number;amount:number;currency:string;status:string;dueAt:string|null;paidAt:string|null;refundedAt:string|null;provider:string;providerPaymentId:string|null;invoiceUrl:string|null;failureReason:string|null;createdAt:string;}
export interface BillingSubscription{id:number;planKey:string;planName:string;status:string;amount:number;currency:string;billingInterval:string;trialStartAt:string|null;trialEndAt:string|null;currentPeriodStart:string|null;currentPeriodEnd:string|null;canceledAt:string|null;provider:string|null;providerSubscriptionId:string|null;}
export interface BillingData{account:{id:number;company:string;email:string;document:string};plans:BillingPlan[];subscription:BillingSubscription|null;payments:BillingPayment[];}
export const api={
 login:async(email:string,password:string)=>{const result=await request<AuthResponse>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});notifyAuthenticated();return result;},
 register:async(name:string,email:string,password:string)=>{const result=await request<AuthResponse>('/auth/register',{method:'POST',body:JSON.stringify({name,email,password})});notifyAuthenticated();return result;},
 logout:()=>request<{success:boolean}>('/auth/logout',{method:'POST'}),requestPasswordReset:(email:string)=>request<{message:string}>('/auth/password-reset/request',{method:'POST',body:JSON.stringify({email})}),resetPassword:(email:string,code:string,password:string)=>request<{success:boolean}>('/auth/password-reset/confirm',{method:'POST',body:JSON.stringify({email,code,password})}),
 webauthnRegisterOptions:()=>request<PublicKeyCredentialCreationOptionsJSON>('/auth/webauthn/register/options',{method:'POST'}),webauthnRegisterVerify:(response:RegistrationResponseJSON)=>request<{success:boolean}>('/auth/webauthn/register/verify',{method:'POST',body:JSON.stringify(response)}),webauthnAuthenticationOptions:(email?:string)=>request<PublicKeyCredentialRequestOptionsJSON>('/auth/webauthn/authenticate/options',{method:'POST',body:JSON.stringify(email?.trim()?{email:email.trim()}: {})}),webauthnAuthenticationVerify:async(response:AuthenticationResponseJSON)=>{const result=await request<AuthResponse>('/auth/webauthn/authenticate/verify',{method:'POST',body:JSON.stringify(response)});notifyAuthenticated();return result;},
 getMe:()=>request<UserProfile>('/users/me'),getAdminAccess:()=>request<{allowed:boolean}>('/users/admin/access'),getDashboardSummary:async(days:string='30')=>normalizeDashboardSummary(await request<unknown>(`/dashboard/summary?days=${encodeURIComponent(days)}`)),getTeam:()=>request<TeamMember[]>('/users/admin/team'),createTeamMember:(data:{name:string;email:string;password:string;phone:string;role:string})=>request<TeamMember>('/users/admin/team',{method:'POST',body:JSON.stringify(data)}),deleteTeamMember:(id:number)=>request<{success:boolean}>(`/users/admin/team/${id}`,{method:'DELETE'}),updateProfile:(data:Omit<UserProfile,'id'>)=>request<UserProfile>('/users/me',{method:'PUT',body:JSON.stringify(data)}),getCompanyProfile:()=>request<CompanyProfileData|null>('/users/admin/company-profile'),updateCompanyProfile:(data:CompanyProfileData)=>request<CompanyProfileData>('/users/admin/company-profile',{method:'PUT',body:JSON.stringify(data)}),getBilling:()=>request<BillingData>('/dashboard/billing'),subscribeBilling:(planKey:string,billingType:'PIX'|'CREDIT_CARD'|'BOLETO')=>request<{success:boolean;subscriptionId:number;providerSubscriptionId:string;payments:{id:string;status:string;invoiceUrl:string|null;dueDate:string|null;value:number;billingType:string}[]}>('/dashboard/billing/subscribe',{method:'POST',body:JSON.stringify({planKey,billingType})}),refreshBilling:()=>request<{payments:any[]}>('/dashboard/billing/refresh',{method:'POST'}),uploadPhoto:(file:File,folder:'attendances'|'signatures'|'profiles'='attendances')=>uploadFile<{key:string;url:string}>(file,folder),addAttendancePhoto:(orderId:string,attendanceId:string,file:File)=>uploadFile<{key:string;url:string}>(file,'attendances').then(({key,url})=>request<{photo:{id:string;key:string;dataUrl:string;name:string}}>(`/orders/${encodeURIComponent(orderId)}/attendances/${encodeURIComponent(attendanceId)}/photos`,{method:'POST',body:JSON.stringify({key,url,name:file.name})})),deleteAttendancePhoto:(orderId:string,attendanceId:string,photoId:string)=>request<{success:boolean}>(`/orders/${encodeURIComponent(orderId)}/attendances/${encodeURIComponent(attendanceId)}/photos/${encodeURIComponent(photoId)}`,{method:'DELETE'}),
 getOrders:async()=>{const orders=await request<unknown>('/orders');return Array.isArray(orders)?orders.map(normalizeOrder):[];},createOrder:async(order:ServiceOrder)=>normalizeOrder(await request<ServiceOrder>('/orders',{method:'POST',body:JSON.stringify(order)})),updateOrder:async(id:string,order:Partial<ServiceOrder>)=>normalizeOrder(await request<ServiceOrder>(`/orders/${id}`,{method:'PUT',body:JSON.stringify(order)})),deleteOrder:(id:string)=>request<{success:boolean}>(`/orders/${id}`,{method:'DELETE'}),getClients:()=>request<Client[]>('/clients'),createClient:(client:Client)=>request<Client>('/clients',{method:'POST',body:JSON.stringify(client)}),updateClient:(id:string,client:Partial<Client>)=>request<Client>(`/clients/${id}`,{method:'PUT',body:JSON.stringify(client)}),deleteClient:(id:string)=>request<{success:boolean}>(`/clients/${id}`,{method:'DELETE'})
};
type AuthResponse={user:UserProfile;token?:never};
