import { useEffect, useState } from 'react';
import { ArrowLeft, CreditCard, RefreshCw, WalletCards } from 'lucide-react';

type Payment={id:number;accountId:number;company:string;amount:number;currency:string;status:string;dueAt:string|null;paidAt:string|null;provider:string|null;plan:string;invoiceUrl?:string|null};
type Plan={id:number;key:string;name:string;amount:number;active:boolean;billingInterval:string};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:string|null)=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
const statusLabel=(v:string)=>({paid:'Pago',pending:'Pendente',open:'Aberto',failed:'Falhou',refunded:'Estornado',cancelled:'Cancelado'}[v]||v||'—');
const cookie=(name:string)=>document.cookie.split('; ').find(x=>x.startsWith(name+'='))?.split('=')[1]||'';

export default function BackofficeBilling(){
 const [payments,setPayments]=useState<Payment[]>([]); const [plans,setPlans]=useState<Plan[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [p,pl]=await Promise.all([fetch('/api/dashboard/backoffice-payments',{credentials:'include'}),fetch('/api/dashboard/backoffice-plans',{credentials:'include'})]);if([p.status,pl.status].some(s=>s===401||s===403)){window.location.href='/backoffice/login';return;}const pj=await p.json(),plj=await pl.json();if(!p.ok)throw new Error(pj.error||'Falha ao carregar pagamentos');if(!pl.ok)throw new Error(plj.error||'Falha ao carregar planos');setPayments(pj.payments||[]);setPlans(plj.plans||[]);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar billing');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const logout=async()=>{await fetch('/api/dashboard/backoffice-logout',{method:'POST',credentials:'include',headers:{'X-CSRF-Token':cookie('qtecnico_backoffice_csrf')}}).catch(()=>{});window.location.href='/backoffice/login';};
 if(loading)return <main className="min-h-screen bg-slate-950 text-white flex items-center justify-center"><RefreshCw className="animate-spin text-cyan-400"/></main>;
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900 px-5 py-4"><div className="mx-auto flex max-w-7xl items-center justify-between"><button onClick={()=>window.location.href='/backoffice'} className="flex items-center gap-2 text-slate-300"><ArrowLeft size={18}/> Backoffice</button><button onClick={logout} className="text-sm text-slate-400">Sair</button></div></header><div className="mx-auto max-w-7xl p-5 sm:p-6"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">Billing SaaS</h1><p className="mt-1 text-slate-400">Planos e histórico de pagamentos das assinaturas QTECNICO.</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300"><RefreshCw size={16}/> Atualizar</button></div>{error&&<div className="mb-5 rounded-xl border border-red-900/50 bg-red-950/30 p-4 text-red-300">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{plans.map(p=><div key={p.key} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><CreditCard className="mb-3 text-cyan-400" size={20}/><p className="text-sm text-slate-400">{p.name}</p><strong className="text-2xl">{money(p.amount)}</strong><p className="text-xs text-slate-500">/{p.billingInterval==='month'?'mês':p.billingInterval}</p></div>)}</div>
 <section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5 flex items-center gap-3"><WalletCards className="text-cyan-400"/><div><h2 className="font-semibold">Pagamentos</h2><p className="text-sm text-slate-500">Últimos 200 lançamentos de assinatura.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-slate-950/60 text-slate-400"><tr>{['Empresa','Plano','Valor','Status','Vencimento','Pago em','Origem'].map(h=><th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{payments.map(p=><tr key={p.id} className="border-t border-slate-800"><td className="px-5 py-4">{p.company}</td><td className="px-5 py-4 uppercase text-cyan-300">{p.plan}</td><td className="px-5 py-4">{money(p.amount)}</td><td className="px-5 py-4">{statusLabel(p.status)}</td><td className="px-5 py-4">{date(p.dueAt)}</td><td className="px-5 py-4">{date(p.paidAt)}</td><td className="px-5 py-4">{p.provider||'—'}</td></tr>)}</tbody></table></div>{payments.length===0&&<div className="p-8 text-center text-slate-500">Nenhum pagamento registrado.</div>}</section></div></main>;
}
