import { useEffect, useState } from 'react';
import { Building2, CreditCard, LogOut, ShieldCheck, Users, WalletCards, RefreshCw, Banknote } from 'lucide-react';

type Account={id:number;company:string;document:string;owner:string;email:string;plan:string;planName:string;status:string;periodEnd:string|null;trialEnd:string|null;subscriptionId:number|null;amount:number;createdAt:string};
type Summary={metrics:{total:number;active:number;trials:number;overdue:number;cancelled:number;mrr:number;receivedThisMonth:number;receivable:number};plans:{plan_key:string;count:number}[]};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const cookie=(name:string)=>document.cookie.split('; ').find(x=>x.startsWith(name+'='))?.split('=')[1]||'';
const statusLabel=(status:string)=>({active:'Ativa',trial:'Em teste',trialing:'Em teste',past_due:'Em atraso',overdue:'Em atraso',unpaid:'Não paga',cancelled:'Cancelada',canceled:'Cancelada'}[status]||status||'—');

export default function BackofficeDashboard(){
 const [summary,setSummary]=useState<Summary|null>(null); const [accounts,setAccounts]=useState<Account[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [s,a]=await Promise.all([fetch('/api/dashboard/backoffice-summary',{credentials:'include'}),fetch('/api/dashboard/backoffice-accounts',{credentials:'include'})]);if(s.status===401||a.status===401||s.status===403||a.status===403){window.location.href='/backoffice/login';return;}const sd=await s.json();const ad=await a.json();if(!s.ok)throw new Error(sd.error||'Falha ao carregar o Backoffice');if(!a.ok)throw new Error(ad.error||'Falha ao carregar as contas');setSummary(sd);setAccounts(ad.accounts||[]);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const logout=async()=>{await fetch('/api/dashboard/backoffice-logout',{method:'POST',credentials:'include',headers:{'X-CSRF-Token':cookie('qtecnico_backoffice_csrf')}}).catch(()=>{});window.location.href='/backoffice/login';};
 if(loading)return <main className="min-h-screen bg-slate-950 text-white flex items-center justify-center"><div className="text-center"><RefreshCw className="mx-auto mb-3 animate-spin text-cyan-400"/><p>Carregando Backoffice...</p></div></main>;
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900/90 px-5 py-4"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-500/10 p-2 text-cyan-400"><ShieldCheck size={22}/></div><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-400">QTECNICO</p><h1 className="font-semibold">Backoffice SaaS</h1></div></div><div className="flex gap-2"><button onClick={()=>void load()} className="rounded-lg border border-slate-700 p-2 text-slate-300" title="Atualizar"><RefreshCw size={17}/></button><button onClick={logout} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300"><LogOut size={16}/> Sair</button></div></div></header>
 <div className="mx-auto max-w-7xl p-5 sm:p-6"><div className="mb-7"><h2 className="text-3xl font-semibold">Gestão de contas</h2><p className="mt-1 text-slate-400">Visão macro da base SaaS, assinaturas e recebimentos.</p></div>{error&&<div className="mb-5 rounded-xl border border-red-900/50 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Building2,'Contas',summary?.metrics.total||0],[Users,'Ativas',summary?.metrics.active||0],[Users,'Em teste',summary?.metrics.trials||0],[CreditCard,'MRR',money(summary?.metrics.mrr||0)]].map(([Icon,label,value])=><div key={String(label)} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><Icon className="mb-4 text-cyan-400" size={21}/><p className="text-sm text-slate-400">{String(label)}</p><strong className="mt-1 block text-2xl">{String(value)}</strong></div>)}</div>
 <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><WalletCards className="mb-3 text-cyan-400" size={21}/><p className="text-sm text-slate-400">Recebido no mês</p><strong className="mt-1 block text-2xl">{money(summary?.metrics.receivedThisMonth||0)}</strong></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><Banknote className="mb-3 text-cyan-400" size={21}/><p className="text-sm text-slate-400">A receber</p><strong className="mt-1 block text-2xl">{money(summary?.metrics.receivable||0)}</strong></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><CreditCard className="mb-3 text-amber-400" size={21}/><p className="text-sm text-slate-400">Inadimplentes</p><strong className="mt-1 block text-2xl">{summary?.metrics.overdue||0}</strong></div></div>
 <section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5"><h3 className="font-semibold">Contas SaaS</h3><p className="text-sm text-slate-500">Assinatura e situação financeira por empresa. Pagamentos SaaS são independentes de pagamentos das ordens.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-950/60 text-slate-400"><tr>{['Empresa','Responsável','Plano','Valor','Status','Vencimento','Cadastro'].map(h=><th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={a.id} className="border-t border-slate-800"><td className="px-5 py-4"><div className="font-medium">{a.company}</div><div className="text-xs text-slate-500">{a.document||'Documento não informado'}</div></td><td className="px-5 py-4"><div>{a.owner}</div><div className="text-xs text-slate-500">{a.email}</div></td><td className="px-5 py-4"><div className="text-cyan-300">{a.planName}</div><div className="text-xs uppercase text-slate-500">{a.plan}</div></td><td className="px-5 py-4">{money(a.amount)}</td><td className="px-5 py-4">{statusLabel(a.status)}</td><td className="px-5 py-4">{a.periodEnd?new Date(a.periodEnd).toLocaleDateString('pt-BR'):'—'}</td><td className="px-5 py-4">{new Date(a.createdAt).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div>{accounts.length===0&&<div className="p-8 text-center text-slate-500">Nenhuma conta encontrada.</div>}</section>
 <div className="mt-6 rounded-2xl border border-cyan-900/40 bg-cyan-950/20 p-4 text-sm text-cyan-100"><strong>Billing SaaS:</strong> estrutura própria criada para planos, assinaturas, pagamentos e histórico de eventos. Nenhum pagamento de ordens é usado como cobrança de assinatura.</div></div></main>;
}
