import { useEffect, useState } from 'react';
import { Building2, CreditCard, LogOut, ShieldCheck, Users, WalletCards, RefreshCw, Banknote, CheckCircle2, XCircle } from 'lucide-react';

type Account={id:number;company:string;document:string;owner:string;email:string;plan:string;planName:string;status:string;periodEnd:string|null;trialEnd:string|null;subscriptionId:number|null;amount:number;createdAt:string};
type Summary={metrics:{total:number;active:number;trials:number;overdue:number;cancelled:number;mrr:number;receivedThisMonth:number;receivable:number};plans:{plan_key:string;count:number}[]};
type AsaasStatus={environment:string;baseUrl:string;authenticated:boolean};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const cookie=(name:string)=>document.cookie.split('; ').find(x=>x.startsWith(name+'='))?.split('=')[1]||'';
const statusLabel=(status:string)=>({active:'Ativa',trial:'Em teste',trialing:'Em teste',past_due:'Em atraso',overdue:'Em atraso',unpaid:'Não paga',cancelled:'Cancelada',canceled:'Cancelada'}[status]||status||'—');

export default function BackofficeDashboard(){
 const [summary,setSummary]=useState<Summary|null>(null); const [accounts,setAccounts]=useState<Account[]>([]); const [asaas,setAsaas]=useState<AsaasStatus|null>(null); const [loading,setLoading]=useState(true); const [asaasLoading,setAsaasLoading]=useState(false); const [error,setError]=useState(''); const [asaasError,setAsaasError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [s,a]=await Promise.all([fetch('/api/dashboard/backoffice-summary',{credentials:'include'}),fetch('/api/dashboard/backoffice-accounts',{credentials:'include'})]);if(s.status===401||a.status===401||s.status===403||a.status===403){window.location.href='/backoffice/login';return;}const sd=await s.json();const ad=await a.json();if(!s.ok)throw new Error(sd.error||'Falha ao carregar o Backoffice');if(!a.ok)throw new Error(ad.error||'Falha ao carregar as contas');setSummary(sd);setAccounts(ad.accounts||[]);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar');}finally{setLoading(false);}};
 const checkAsaas=async()=>{setAsaasLoading(true);setAsaasError('');try{const r=await fetch('/api/dashboard/backoffice/asaas-status',{credentials:'include'});const data=await r.json();if(r.status===401||r.status===403){window.location.href='/backoffice/login';return;}if(!r.ok)throw new Error(data.error||'Não foi possível autenticar no Asaas Sandbox');setAsaas(data);}catch(e){setAsaas(null);setAsaasError(e instanceof Error?e.message:'Falha ao verificar Asaas');}finally{setAsaasLoading(false);}};
 useEffect(()=>{void load();void checkAsaas();},[]);
 const logout=async()=>{await fetch('/api/dashboard/backoffice-logout',{method:'POST',credentials:'include',headers:{'X-CSRF-Token':cookie('qtecnico_backoffice_csrf')}}).catch(()=>{});window.location.href='/backoffice/login';};
 if(loading)return <main className="min-h-screen bg-slate-950 text-white flex items-center justify-center"><div className="text-center"><RefreshCw className="mx-auto mb-3 animate-spin text-cyan-400"/><p>Carregando Backoffice...</p></div></main>;
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900/90 px-5 py-4"><div className="mx-auto flex max-w-7xl items-center justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-cyan-500/10 p-2 text-cyan-400"><ShieldCheck size={22}/></div><div><p className="text-xs uppercase tracking-[0.2em] text-cyan-400">QTECNICO</p><h1 className="font-semibold">Backoffice SaaS</h1></div></div><div className="flex gap-2"><button onClick={()=>window.location.href='/backoffice/billing'} className="flex items-center gap-2 rounded-lg border border-cyan-900/60 bg-cyan-500/10 px-3 py-2 text-sm text-cyan-300"><CreditCard size={16}/> Billing</button><button onClick={()=>void load()} className="rounded-lg border border-slate-700 p-2 text-slate-300" title="Atualizar"><RefreshCw size={17}/></button><button onClick={logout} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300"><LogOut size={16}/> Sair</button></div></div></header>
 <div className="mx-auto max-w-7xl p-5 sm:p-6"><div className="mb-7"><h2 className="text-3xl font-semibold">Gestão de contas</h2><p className="mt-1 text-slate-400">Visão macro da base SaaS, assinaturas e recebimentos.</p></div>{error&&<div className="mb-5 rounded-xl border border-red-900/50 bg-red-950/30 p-4 text-sm text-red-300">{error}</div>}
 <section className="mb-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldCheck size={19} className="text-cyan-400"/><h3 className="font-semibold">Gateway de pagamentos</h3></div><p className="mt-1 text-sm text-slate-500">Conexão usada pelo QTECNICO para homologação financeira.</p></div><button onClick={()=>void checkAsaas()} disabled={asaasLoading} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-200 disabled:opacity-50"><RefreshCw size={15} className={asaasLoading?'animate-spin':''}/> Verificar conexão</button></div><div className="mt-4 flex flex-wrap items-center gap-3">{asaas?.authenticated?<span className="inline-flex items-center gap-2 rounded-full border border-emerald-900/50 bg-emerald-950/30 px-3 py-1.5 text-sm text-emerald-300"><CheckCircle2 size={15}/> Asaas Sandbox conectado</span>:<span className="inline-flex items-center gap-2 rounded-full border border-amber-900/50 bg-amber-950/30 px-3 py-1.5 text-sm text-amber-300">{asaasLoading?'Verificando...':'Não verificado'}</span>}{asaas&&<span className="text-xs text-slate-500">{asaas.baseUrl}</span>}{asaasError&&<span className="inline-flex items-center gap-2 text-sm text-red-300"><XCircle size={15}/>{asaasError}</span>}</div></section>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([ { icon: Building2, label: 'Contas', value: summary?.metrics.total || 0 }, { icon: Users, label: 'Ativas', value: summary?.metrics.active || 0 }, { icon: Users, label: 'Em teste', value: summary?.metrics.trials || 0 }, { icon: CreditCard, label: 'MRR', value: money(summary?.metrics.mrr || 0) } ]).map(({ icon: Icon, label, value })=><div key={label} className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><Icon className="mb-4 text-cyan-400" size={21}/><p className="text-sm text-slate-400">{label}</p><strong className="mt-1 block text-2xl">{value}</strong></div>)}</div>
 <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><WalletCards className="mb-3 text-cyan-400" size={21}/><p className="text-sm text-slate-400">Recebido no mês</p><strong className="mt-1 block text-2xl">{money(summary?.metrics.receivedThisMonth||0)}</strong></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><Banknote className="mb-3 text-cyan-400" size={21}/><p className="text-sm text-slate-400">A receber</p><strong className="mt-1 block text-2xl">{money(summary?.metrics.receivable||0)}</strong></div><div className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><CreditCard className="mb-3 text-amber-400" size={21}/><p className="text-sm text-slate-400">Inadimplentes</p><strong className="mt-1 block text-2xl">{summary?.metrics.overdue||0}</strong></div></div>
 <section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5"><h3 className="font-semibold">Contas SaaS</h3><p className="text-sm text-slate-500">Assinatura e situação financeira por empresa. Pagamentos SaaS são independentes de pagamentos das ordens.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-950/60 text-slate-400"><tr>{['Empresa','Responsável','Plano','Valor','Status','Vencimento','Cadastro'].map(h=><th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{accounts.map(a=><tr key={a.id} onClick={()=>window.location.href=`/backoffice/account?id=${a.id}`} className="cursor-pointer border-t border-slate-800 transition hover:bg-slate-800/60" title="Abrir detalhes da conta"><td className="px-5 py-4"><div className="font-medium">{a.company}</div><div className="text-xs text-slate-500">{a.document||'Documento não informado'}</div></td><td className="px-5 py-4"><div>{a.owner}</div><div className="text-xs text-slate-500">{a.email}</div></td><td className="px-5 py-4"><div className="text-cyan-300">{a.planName}</div><div className="text-xs uppercase text-slate-500">{a.plan}</div></td><td className="px-5 py-4">{money(a.amount)}</td><td className="px-5 py-4">{statusLabel(a.status)}</td><td className="px-5 py-4">{a.periodEnd?new Date(a.periodEnd).toLocaleDateString('pt-BR'):'—'}</td><td className="px-5 py-4">{new Date(a.createdAt).toLocaleDateString('pt-BR')}</td></tr>)}</tbody></table></div>{accounts.length===0&&<div className="p-8 text-center text-slate-500">Nenhuma conta encontrada.</div>}</section>
 <div className="mt-6 rounded-2xl border border-cyan-900/40 bg-cyan-950/20 p-4 text-sm text-cyan-100"><strong>Billing SaaS:</strong> estrutura própria criada para planos, assinaturas, pagamentos e histórico de eventos. Nenhum pagamento de ordens é usado como cobrança de assinatura.</div></div></main>;
}
