import type { TrialInfo } from './api';
import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, CreditCard, ExternalLink, PauseCircle, PlayCircle, RefreshCw, XCircle } from 'lucide-react';

type Plan={key:string;name:string;amount:number;billingInterval:string;active:boolean};
type Payment={id:number;amount:number;status:string;dueAt:string|null;paidAt:string|null;refundedAt:string|null;provider:string|null;providerPaymentId:string|null;invoiceUrl:string|null;failureReason:string|null;metadata:any;plan:string;createdAt:string};
type Event={id:number;eventType:string;source:string;actorName:string|null;createdAt:string;payload:any};
type Account={trial:TrialInfo;id:number;company:string;legalName:string|null;document:string;owner:string;email:string;billingEmail:string;phone:string|null;createdAt:string;legacyPlan:string;legacyStatus:string;subscription:any|null};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=(v:string|null)=>v?new Date(v).toLocaleString('pt-BR'):'—';
const shortDate=(v:string|null)=>v?new Date(v).toLocaleDateString('pt-BR'):'—';
const labelStatus=(v:string)=>({active:'Ativa',trial:'Em teste',trialing:'Em teste',past_due:'Inadimplente',overdue:'Inadimplente',unpaid:'Não paga',paused:'Suspensa',cancelled:'Cancelada',canceled:'Cancelada',paid:'Pago',pending:'Pendente',failed:'Falhou',refunded:'Estornado'}[v]||v||'—');
const cookie=(name:string)=>document.cookie.split('; ').find(x=>x.startsWith(name+'='))?.split('=')[1]||'';
const meta=(obj:any,key:string)=>obj&&typeof obj==='object'&&obj[key]!=null?String(obj[key]):'';

export default function BackofficeAccount(){
 const id=Number(new URLSearchParams(window.location.search).get('id')||0);
 const [data,setData]=useState<{account:Account;payments:Payment[];events:Event[];plans:Plan[];trialEvents:{id:number;action:string;actor_user_id:number|null;created_at:string;before_state:unknown;after_state:unknown}[]}|null>(null);
 const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [busy,setBusy]=useState('');
 const load=async()=>{if(!id){setError('Conta inválida.');setLoading(false);return;}setLoading(true);setError('');try{const r=await fetch(`/api/dashboard/backoffice/account/${id}`,{credentials:'include'});if(r.status===401||r.status===403){window.location.href='/backoffice/login';return;}const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao carregar conta');setData(j);}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar conta');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[id]);
 const action=async(actionName:string,extra:any={})=>{setBusy(actionName);setError('');try{const r=await fetch(`/api/dashboard/backoffice/account/${id}/action`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':cookie('qtecnico_backoffice_csrf')},body:JSON.stringify({action:actionName,...extra})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Ação não realizada');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível executar a ação');}finally{setBusy('');}};
 const trialAction=async(actionName:'start'|'extend'|'end')=>{setBusy('trial');setError('');try{const r=await fetch(`/api/dashboard/backoffice/account/${id}/trial`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json','X-CSRF-Token':cookie('qtecnico_backoffice_csrf')},body:JSON.stringify({action:actionName})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Falha ao alterar trial');await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao alterar trial');}finally{setBusy('');}};
 const manualPayment=()=>{const value=window.prompt('Valor do pagamento (R$):',String(data?.account.subscription?.amount||0));if(value===null)return;const amount=Number(value.replace(',','.'));if(!Number.isFinite(amount)||amount<0){setError('Informe um valor válido.');return;}void action('manual_payment',{amount});};
 const extendPeriod=()=>{const current=data?.account.subscription?.currentPeriodEnd;const initial=current?new Date(current).toISOString().slice(0,10):'';const value=window.prompt('Nova data final do período (AAAA-MM-DD):',initial);if(!value)return;const d=new Date(`${value}T23:59:59`);if(Number.isNaN(d.getTime())){setError('Informe uma data válida.');return;}void action('extend_period',{periodEnd:d.toISOString()});};
 const logout=async()=>{await fetch('/api/dashboard/backoffice-logout',{method:'POST',credentials:'include',headers:{'X-CSRF-Token':cookie('qtecnico_backoffice_csrf')}}).catch(()=>{});window.location.href='/backoffice/login';};
 if(loading)return <main className="min-h-screen bg-slate-950 text-white flex items-center justify-center"><RefreshCw className="animate-spin text-cyan-400"/></main>;
 if(!data)return <main className="min-h-screen bg-slate-950 text-white p-6"><button onClick={()=>window.location.href='/backoffice'}>← Backoffice</button><div className="mx-auto mt-10 max-w-xl rounded-2xl border border-red-900/50 bg-red-950/30 p-5 text-red-300">{error||'Conta não encontrada.'}</div></main>;
 const {account,payments,events,plans}=data; const subscription=account.subscription; const currentPlan=plans.find(p=>p.key===(subscription?.planKey||account.legacyPlan));
 const latestPayment=payments[0]; const paymentMeta=latestPayment?.metadata||{}; const subscriptionMeta=subscription?.metadata||{};
 const paymentMethod=meta(paymentMeta,'paymentMethod')||meta(paymentMeta,'payment_method')||meta(subscriptionMeta,'paymentMethod')||meta(subscriptionMeta,'payment_method');
 const cardBrand=meta(paymentMeta,'cardBrand')||meta(paymentMeta,'card_brand'); const cardLast4=meta(paymentMeta,'cardLast4')||meta(paymentMeta,'card_last4');
 const payerDocument=meta(paymentMeta,'payerDocument')||meta(paymentMeta,'payer_document')||account.document;
 return <main className="min-h-screen bg-slate-950 text-white"><header className="border-b border-slate-800 bg-slate-900 px-5 py-4"><div className="mx-auto flex max-w-7xl items-center justify-between"><button onClick={()=>window.location.href='/backoffice'} className="flex items-center gap-2 text-slate-300"><ArrowLeft size={18}/> Contas</button><button onClick={logout} className="text-sm text-slate-400">Sair</button></div></header>
 <div className="mx-auto max-w-7xl p-5 sm:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-cyan-400">Conta #{account.id}</p><h1 className="text-3xl font-semibold">{account.company}</h1><p className="mt-1 text-slate-400">{account.owner} · {account.email}</p></div><button onClick={()=>void load()} className="flex items-center gap-2 rounded-lg border border-slate-700 px-3 py-2 text-sm text-slate-300"><RefreshCw size={16}/> Atualizar</button></div>
 {error&&<div className="mb-5 rounded-xl border border-red-900/50 bg-red-950/30 p-4 text-red-300">{error}</div>}
 <div className="grid gap-4 lg:grid-cols-3"><section className="rounded-2xl border border-slate-800 bg-slate-900 p-5 lg:col-span-2"><div className="flex items-center justify-between gap-4"><div><p className="text-sm text-slate-400">Assinatura</p><h2 className="mt-1 text-xl font-semibold">{currentPlan?.name||subscription?.planKey||account.legacyPlan}</h2></div><span className="rounded-full bg-slate-800 px-3 py-1 text-sm">{labelStatus(subscription?.status||account.legacyStatus)}</span></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-slate-500">Mensalidade</p><strong>{money(Number(subscription?.amount??0))}</strong></div><div><p className="text-xs text-slate-500">Próximo vencimento</p><strong>{date(subscription?.currentPeriodEnd)}</strong></div><div><p className="text-xs text-slate-500">Fim do teste</p><strong>{date(account.trial.endsAt)}</strong></div><div><p className="text-xs text-slate-500">Cadastro</p><strong>{date(account.createdAt)}</strong></div></div></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">Empresa</p><div className="mt-3 space-y-2 text-sm"><p><span className="text-slate-500">Razão social:</span> {account.legalName||'—'}</p><p><span className="text-slate-500">CNPJ/Documento:</span> {account.document||'—'}</p><p><span className="text-slate-500">Telefone:</span> {account.phone||'—'}</p></div></section></div>
 <section className="mt-6 rounded-2xl border border-cyan-900/50 bg-slate-900 p-5">
  <h2 className="font-semibold">Degustação Business</h2>
  <p className="mt-2 text-sm text-slate-300">{{not_started:'Não iniciada',active:'Ativa',expired:'Expirada',ended:'Encerrada'}[account.trial.status]} · {account.trial.daysRemaining} dias restantes</p>
  <p className="mt-2 text-sm text-slate-400">Início: {date(account.trial.startedAt)} · Fim: {date(account.trial.endsAt)}</p>
  <p className="mt-2 text-sm text-slate-400">Plano contratado: {plans.find(plan=>plan.key===account.legacyPlan)?.name||account.legacyPlan}. Degustação sem cobrança, separada da assinatura.</p>
  <div className="mt-4 flex flex-wrap gap-3">{['essential','pro'].includes(account.legacyPlan)&&!account.trial.active&&<button disabled={!!busy} onClick={()=>void trialAction('start')} className="rounded-lg bg-cyan-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">Ativar trial Business por 14 dias</button>}<button disabled={!!busy||!['active','expired'].includes(account.trial.status)} onClick={()=>void trialAction('extend')} className="rounded-lg border border-cyan-700 px-4 py-2 disabled:opacity-50">Estender +7 dias</button><button disabled={!!busy||!['active','expired'].includes(account.trial.status)} onClick={()=>void trialAction('end')} className="rounded-lg border border-amber-700 px-4 py-2 disabled:opacity-50">Encerrar trial</button></div>
  <details className="mt-4 text-sm text-slate-400"><summary>Histórico da degustação</summary>{data.trialEvents.map(event=><p className="mt-2" key={event.id}>{date(event.created_at)} · {{registration:'Trial iniciado',start:'Trial ativado pelo Backoffice',extend:'Estendido em 7 dias',end:'Trial encerrado'}[event.action]||event.action} · {event.actor_user_id ? `Administrador #${event.actor_user_id}` : 'Cadastro automático'}</p>)}</details>
 </section>
 <section className="mt-6 rounded-2xl border border-cyan-900/50 bg-slate-900 p-5"><div className="flex items-center gap-2"><CreditCard className="text-cyan-400" size={21}/><div><h2 className="font-semibold">Cobrança e pagamentos</h2><p className="text-sm text-slate-500">Informações financeiras da conta dentro do perfil da empresa.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-slate-950/60 p-4"><p className="text-xs text-slate-500">Status da assinatura</p><p className="mt-1 font-medium">{labelStatus(subscription?.status||account.legacyStatus)}</p></div><div className="rounded-xl bg-slate-950/60 p-4"><p className="text-xs text-slate-500">Plano / periodicidade</p><p className="mt-1 font-medium">{currentPlan?.name||subscription?.planKey||'—'} · {subscription?.billingInterval||'—'}</p></div><div className="rounded-xl bg-slate-950/60 p-4"><p className="text-xs text-slate-500">Valor recorrente</p><p className="mt-1 font-medium">{money(Number(subscription?.amount??0))}</p></div><div className="rounded-xl bg-slate-950/60 p-4"><p className="text-xs text-slate-500">Próxima cobrança</p><p className="mt-1 font-medium">{shortDate(subscription?.currentPeriodEnd)}</p></div></div><div className="mt-4 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-medium">Dados de faturamento</h3><div className="mt-3 space-y-2 text-sm"><p><span className="text-slate-500">E-mail de cobrança:</span> {account.billingEmail||account.email||'—'}</p><p><span className="text-slate-500">Pagador CPF/CNPJ:</span> {payerDocument||'—'}</p><p><span className="text-slate-500">Provedor:</span> {subscription?.provider||latestPayment?.provider||'Ainda não definido'}</p><p><span className="text-slate-500">ID da assinatura:</span> {subscription?.providerSubscriptionId||'—'}</p></div></div><div className="rounded-xl border border-slate-800 p-4"><h3 className="font-medium">Forma de pagamento</h3><div className="mt-3 space-y-2 text-sm"><p><span className="text-slate-500">Método:</span> {paymentMethod||'Não informado'}</p><p><span className="text-slate-500">Cartão:</span> {cardBrand&&cardLast4?`${cardBrand} •••• ${cardLast4}`:'Não informado'}</p><p><span className="text-slate-500">Último pagamento:</span> {latestPayment?.paidAt?`${money(latestPayment.amount)} em ${date(latestPayment.paidAt)}`:'Nenhum pagamento'}</p>{latestPayment?.invoiceUrl&&<a href={latestPayment.invoiceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-cyan-400">Ver fatura <ExternalLink size={14}/></a>}</div></div></div>{!paymentMethod&&<p className="mt-4 text-xs text-slate-500">A forma de pagamento ainda não está registrada no QTECNICO. Quando o gateway for integrado, serão exibidos apenas dados seguros/tokenizados, como tipo do método e últimos 4 dígitos do cartão.</p>}</section>
 <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><div className="flex items-center gap-2"><CreditCard className="text-cyan-400" size={20}/><h2 className="font-semibold">Ações administrativas</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm text-slate-400 lg:col-span-2">Plano<select id="bo-plan" defaultValue={subscription?.planKey||account.legacyPlan} className="mt-1 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-white">{plans.filter(p=>p.active).map(p=><option key={p.key} value={p.key}>{p.name} — {money(p.amount)}</option>)}</select></label><button disabled={!!busy} onClick={()=>{const el=document.getElementById('bo-plan') as HTMLSelectElement;void action('change_plan',{planKey:el.value});}} className="mt-auto rounded-lg bg-cyan-500 px-4 py-2 font-semibold text-slate-950 disabled:opacity-50">{busy==='change_plan'?'Salvando…':'Alterar plano'}</button><button disabled={!!busy} onClick={()=>void action('activate')} className="flex items-center justify-center gap-2 rounded-lg border border-emerald-800 bg-emerald-950/30 px-4 py-2 text-emerald-300 disabled:opacity-50"><PlayCircle size={17}/>Ativar</button><button disabled={!!busy} onClick={()=>void action('suspend')} className="flex items-center justify-center gap-2 rounded-lg border border-amber-800 bg-amber-950/30 px-4 py-2 text-amber-300 disabled:opacity-50"><PauseCircle size={17}/>Suspender</button><button disabled={!!busy} onClick={()=>void action('cancel')} className="flex items-center justify-center gap-2 rounded-lg border border-red-800 bg-red-950/30 px-4 py-2 text-red-300 disabled:opacity-50"><XCircle size={17}/>Cancelar</button><button disabled={!!busy} onClick={()=>void action('reactivate')} className="flex items-center justify-center gap-2 rounded-lg border border-cyan-800 bg-cyan-950/30 px-4 py-2 text-cyan-300 disabled:opacity-50"><CheckCircle2 size={17}/>Reativar</button><button disabled={!!busy} onClick={manualPayment} className="rounded-lg border border-violet-800 bg-violet-950/30 px-4 py-2 text-violet-300 disabled:opacity-50">{busy==='manual_payment'?'Registrando…':'Registrar pagamento'}</button><button disabled={!!busy} onClick={extendPeriod} className="rounded-lg border border-sky-800 bg-sky-950/30 px-4 py-2 text-sky-300 disabled:opacity-50">{busy==='extend_period'?'Salvando…':'Prorrogar período'}</button></div></section>
 <section className="mt-6 overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><div className="border-b border-slate-800 p-5"><h2 className="font-semibold">Histórico financeiro</h2><p className="text-sm text-slate-500">Cobranças e pagamentos desta conta.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-slate-950/60 text-slate-400"><tr>{['Valor','Status','Vencimento','Pago em','Provedor','ID externo','Fatura'].map(h=><th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{payments.map(p=><tr key={p.id} className="border-t border-slate-800"><td className="px-5 py-4">{money(p.amount)}</td><td className="px-5 py-4">{labelStatus(p.status)}{p.failureReason&&<div className="text-xs text-red-400">{p.failureReason}</div>}</td><td className="px-5 py-4">{date(p.dueAt)}</td><td className="px-5 py-4">{date(p.paidAt)}</td><td className="px-5 py-4">{p.provider||'—'}</td><td className="px-5 py-4">{p.providerPaymentId||'—'}</td><td className="px-5 py-4">{p.invoiceUrl?<a href={p.invoiceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-cyan-400">Abrir <ExternalLink size={14}/></a>:'—'}</td></tr>)}</tbody></table></div>{payments.length===0&&<div className="p-8 text-center text-slate-500">Nenhuma cobrança/pagamento registrado.</div>}</section>
 <section className="mt-6 rounded-2xl border border-slate-800 bg-slate-900 p-5"><h2 className="font-semibold">Auditoria</h2><div className="mt-4 space-y-3">{events.map(e=><div key={e.id} className="rounded-xl border border-slate-800 bg-slate-950/50 p-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>{e.eventType}</strong><span className="text-slate-500">{date(e.createdAt)}</span></div><p className="mt-1 text-slate-400">{e.source}{e.actorName?` · ${e.actorName}`:''}</p><pre className="mt-2 overflow-auto text-xs text-slate-500">{JSON.stringify(e.payload,null,2)}</pre></div>)}{events.length===0&&<p className="text-slate-500">Nenhum evento de auditoria registrado.</p>}</div></section></div></main>;
}
