import { useEffect, useState } from 'react';
import { CalendarClock, Plus, X } from 'lucide-react';
import { api, type PreventivePlan } from './api';

type Props={clientId:string};
const today=()=>new Date().toISOString().slice(0,10);
const fmt=(d:string)=>d?new Date(d+'T12:00:00').toLocaleDateString('pt-BR'):'—';

export default function ClientPreventiveMaintenance({clientId}:Props){
 const[plans,setPlans]=useState<PreventivePlan[]>([]),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const[name,setName]=useState(''),[description,setDescription]=useState(''),[firstDate,setFirstDate]=useState(today()),[interval,setInterval]=useState(30);
 const load=async()=>{try{setPlans(await api.getPreventivePlans(clientId));setError('')}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar as preventivas.')}};
 useEffect(()=>{void load()},[clientId]);
 const save=async()=>{if(!name.trim()){setError('Informe o nome da manutenção.');return}setSaving(true);try{await api.createPreventivePlan({clientId,name:name.trim(),description:description.trim(),intervalDays:interval,firstScheduledDate:firstDate,active:true});setName('');setDescription('');setFirstDate(today());setInterval(30);setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a preventiva.')}finally{setSaving(false)}};
 const toggle=async(p:PreventivePlan)=>{try{await api.updatePreventivePlan(p.id,{name:p.name,description:p.description,intervalDays:p.intervalDays,active:!p.active});await load()}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar a preventiva.')}};
 return <div className="mt-5 border-t border-slate-100 pt-4">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Manutenções preventivas <span className="text-slate-400">({plans.length})</span></h3><p className="text-xs text-slate-500">Cadastre rotinas recorrentes deste cliente.</p></div><button type="button" onClick={()=>setOpen(true)} className="inline-flex items-center gap-1.5 rounded-lg bg-cyan-50 px-3 py-2 text-xs font-semibold text-cyan-700"><Plus size={15}/> Nova preventiva</button></div>
  {error&&<p className="mt-2 text-xs text-red-600">{error}</p>}
  {open&&<div className="mt-3 rounded-xl border border-cyan-100 bg-cyan-50/30 p-4"><div className="mb-3 flex items-center justify-between"><b className="text-sm">Nova manutenção preventiva</b><button onClick={()=>setOpen(false)}><X size={16}/></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Nome / tipo<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Preventiva CFTV" className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/></label><label className="text-xs font-medium">Primeira manutenção<input type="date" value={firstDate} onChange={e=>setFirstDate(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/></label><label className="text-xs font-medium">Recorrência<select value={interval} onChange={e=>setInterval(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"><option value={15}>15 dias</option><option value={30}>30 dias</option><option value={45}>45 dias</option><option value={60}>60 dias</option><option value={90}>90 dias</option><option value={120}>120 dias</option><option value={180}>180 dias</option><option value={365}>365 dias</option></select></label><label className="text-xs font-medium">Descrição / escopo<input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Opcional" className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm"/></label></div><div className="mt-3 flex justify-end"><button disabled={saving} onClick={save} className="rounded-lg bg-cyan-600 px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{saving?'Salvando...':'Adicionar preventiva'}</button></div></div>}
  <div className="mt-3 space-y-2">{plans.map(p=><div key={p.id} className="flex flex-col gap-2 rounded-xl bg-slate-50 px-3 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-2"><CalendarClock size={17} className={p.active?'mt-0.5 text-cyan-600':'mt-0.5 text-slate-400'}/><div><p className="text-sm font-semibold">{p.name}</p><p className="text-xs text-slate-500">A cada {p.intervalDays} dias · próxima {fmt(p.nextScheduledDate)}{p.openOrderId?` · OS ${p.openOrderId}`:''}</p>{p.description&&<p className="mt-1 text-xs text-slate-400">{p.description}</p>}</div></div><button onClick={()=>toggle(p)} className={`self-start rounded-full px-2.5 py-1 text-[11px] font-semibold ${p.active?'bg-emerald-50 text-emerald-700':'bg-slate-200 text-slate-600'}`}>{p.active?'Ativa':'Inativa'}</button></div>)}{!plans.length&&!open&&<p className="text-sm text-slate-500">Nenhuma manutenção preventiva cadastrada.</p>}</div>
 </div>
}
