import { ServiceOrder } from "./types";

export const INITIAL_ORDERS: ServiceOrder[] = [
  {
    id: "OS-2406-001", clientId: "c1", client: "Construtora Alpina Ltda",
    address: "Av. Paulista, 1374 — São Paulo, SP", phone: "(11) 99832-4411",
    type: "Instalação Elétrica", status: "in_progress", date: "2026-06-17", priority: "high",
    description: "Instalação de quadro de distribuição e tomadas industriais.",
    clientValue: 4800,
    expenses: [
      { id: "e1", label: "Quadro de distribuição", amount: 980 },
      { id: "e2", label: "Cabos e conectores", amount: 430 },
      { id: "e3", label: "Deslocamento", amount: 120 },
    ],
    attendances: [
      { id: "a1", startTime: "2026-06-17T08:00:00.000Z", endTime: "2026-06-17T10:30:00.000Z",
        durationSeconds: 9000, description: "Instalação do quadro elétrico principal. Circuitos 1 a 8 concluídos.", photos: [] },
    ],
    paymentStatus: "pending",
  },
  {
    id: "OS-2406-002", clientId: "c2", client: "Residencial Parque Verde",
    address: "Rua das Flores, 88 — Campinas, SP", phone: "(19) 98741-3300",
    type: "Manutenção Preventiva", status: "pending", date: "2026-06-18", priority: "medium",
    description: "Revisão geral do sistema de iluminação e disjuntores.",
    clientValue: 1200,
    expenses: [
      { id: "e1", label: "Disjuntores", amount: 180 },
      { id: "e2", label: "Deslocamento", amount: 80 },
    ],
    attendances: [],
    paymentStatus: "pending",
  },
  {
    id: "OS-2406-003", clientId: "c3", client: "Mercado Bom Preço",
    address: "Rua XV de Novembro, 220 — Santos, SP", phone: "(13) 97654-8800",
    type: "Reparo Urgente", status: "pending", date: "2026-06-17", priority: "high",
    description: "Curto-circuito no setor de câmaras frias.",
    clientValue: 2600,
    expenses: [
      { id: "e1", label: "Materiais elétricos", amount: 520 },
      { id: "e2", label: "Deslocamento", amount: 150 },
    ],
    attendances: [],
    paymentStatus: "pending",
  },
  {
    id: "OS-2406-004", clientId: "c4", client: "Clínica São Lucas",
    address: "Av. Dom Pedro I, 450 — Ribeirão Preto, SP", phone: "(16) 99123-5566",
    type: "Instalação de SPDA", status: "completed", date: "2026-06-15", priority: "low",
    description: "Para-raios e aterramento conforme ABNT NBR 5419.",
    clientValue: 3500,
    expenses: [
      { id: "e1", label: "Haste de aterramento", amount: 620 },
      { id: "e2", label: "Condutor de cobre", amount: 380 },
      { id: "e3", label: "Deslocamento", amount: 200 },
    ],
    attendances: [
      { id: "a2", startTime: "2026-06-15T07:30:00.000Z", endTime: "2026-06-15T12:00:00.000Z",
        durationSeconds: 16200, description: "Instalação completa do SPDA. Aterramento aprovado conforme ABNT NBR 5419.", photos: [] },
    ],
    paymentStatus: "paid",
    paidDate: "2026-06-16",
  },
  {
    id: "OS-2406-005", clientId: "c5", client: "Escola Estadual Tiradentes",
    address: "Rua Independência, 300 — Sorocaba, SP", phone: "(15) 98900-1122",
    type: "Laudo Técnico", status: "cancelled", date: "2026-06-14", priority: "low",
    description: "Laudo de conformidade das instalações elétricas.",
    clientValue: 800, expenses: [], attendances: [],
    paymentStatus: "pending",
  },
  {
    id: "OS-2405-001", clientId: "c1", client: "Construtora Alpina Ltda",
    address: "Av. Paulista, 1374 — São Paulo, SP", phone: "(11) 99832-4411",
    type: "Revisão Elétrica", status: "completed", date: "2026-05-20", priority: "medium",
    description: "Revisão geral das instalações do 3º andar.",
    clientValue: 2200,
    expenses: [{ id: "e1", label: "Materiais", amount: 320 }, { id: "e2", label: "Deslocamento", amount: 80 }],
    attendances: [],
    paymentStatus: "paid",
    paidDate: "2026-05-25",
  },
  {
    id: "OS-2405-002", clientId: "c3", client: "Mercado Bom Preço",
    address: "Rua XV de Novembro, 220 — Santos, SP", phone: "(13) 97654-8800",
    type: "Instalação de Iluminação", status: "completed", date: "2026-05-10", priority: "medium",
    description: "Troca de toda a iluminação do salão principal para LED.",
    clientValue: 3100,
    expenses: [{ id: "e1", label: "Luminárias LED", amount: 1100 }, { id: "e2", label: "Cabeamento", amount: 280 }],
    attendances: [],
    paymentStatus: "paid",
    paidDate: "2026-05-15",
  },
  {
    id: "OS-2404-001", clientId: "c2", client: "Residencial Parque Verde",
    address: "Rua das Flores, 88 — Campinas, SP", phone: "(19) 98741-3300",
    type: "Instalação de AR Condicionado", status: "completed", date: "2026-04-08", priority: "low",
    description: "Instalação elétrica para 4 splits novos.",
    clientValue: 1800,
    expenses: [{ id: "e1", label: "Materiais elétricos", amount: 420 }],
    attendances: [],
    paymentStatus: "paid",
    paidDate: "2026-04-12",
  },
  {
    id: "OS-2404-002", clientId: "c4", client: "Clínica São Lucas",
    address: "Av. Dom Pedro I, 450 — Ribeirão Preto, SP", phone: "(16) 99123-5566",
    type: "Manutenção Preventiva", status: "completed", date: "2026-04-22", priority: "medium",
    description: "Revisão trimestral do sistema elétrico.",
    clientValue: 950,
    expenses: [{ id: "e1", label: "Materiais", amount: 120 }, { id: "e2", label: "Deslocamento", amount: 90 }],
    attendances: [],
    paymentStatus: "pending",
  },
];
