import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, CreditCard, ExternalLink, Loader2, RefreshCw, ShieldCheck } from 'lucide-react';
import { api, type BillingData } from './api';

type Props={onBack:()=>void};
const money=(v:number)=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const statusLabel=(s:string)=>({active:'Ativa',trial:'Em teste',trialing:'Em teste',past_due:'Em atraso',unpaid:'Não paga',cancelled:'Cancelada',canceled:'Cancelada',PENDING:'Pendente',RECEIVED:'Recebida',CONFIRMED:'Confirmada',OVERDUE:'Vencida',REFUNDED:'Estornada'}[s]||s||'—');

export default function SubscriptionBilling({onBack}:Props){
 const [data,setData]=useState<BillingData|null>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [selectedPlan,setSelectedPlan]=useState('medium'); const [billingType,setBillingType]=useState<'PIX'|'CREDIT_CARD'|'BOLETO'>('PIX');
 const load=async()=>{setLoading(true);setError('');try{const value=await api.getBilling();setData(value);if(value.subscription?.planKey)setSelectedPlan(value.subscription.planKey);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a assinatura.');}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const paidOrOpen=useMemo(()=>data?.payments?.find(p=>p.invoiceUrl&&['PENDING','CONFIRMED','OVERDUE','RECEIVED'].includes(p.status)),[data]);
 const subscribe=async()=>{setBusy(true);setError('');try{const result=await api.subscribeBilling(selectedPlan,billingType);if(result.payments?.[0]?.invoiceUrl){window.location.href=result.payments[0].invoiceUrl;return;}await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível iniciar a contratação.');}finally{setBusy(false);}};
 if(loading)return <div className="p-6 lg:p-8"><div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-slate-500">Carregando assinatura...</div></div>;
 return <div className="p-4 sm:p-6 lg:p-8">
   <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-cyan-600">Conta SaaS</p><h1 className="mt-1 flex items-center gap-2 text-3xl font-bold tracking-tight"><CreditCard size={28}/> Assinatura e pagamentos</h1><p className="mt-1 text-sm text-slate-500">Contrate e pague o plano do QTECNICO pelo ambiente da sua empresa.</p></div><button onClick={onBack} className="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-50">Voltar</button></div>
   {error&&<div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
   {data?.subscription?<section className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">Plano atual</p><h2 className="mt-1 text-2xl font-bold text-slate-900">{data.subscription.planName}</h2><p className="mt-1 text-sm text-slate-600">{money(data.subscription.amount)} / mês · {statusLabel(data.subscription.status)}</p></div><CheckCircle2 className="text-emerald-600" size={28}/></div>{paidOrOpen?.invoiceUrl&&<div className="mt-4 flex flex-wrap gap-2"><a href={paidOrOpen.invoiceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white"><ExternalLink size={16}/> Abrir cobrança</a><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold"><RefreshCw size={16}/> Atualizar</button></div>}</section>:<section className="mb-5 rounded-2xl border border-cyan-200 bg-cyan-50 p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-cyan-600" size={21}/><div><h2 className="font-bold text-slate-900">Escolha seu plano</h2><p className="mt-1 text-sm text-slate-600">A contratação cria a assinatura no Asaas Sandbox e abre a página de pagamento para você concluir o pagamento.</p></div></div></section>}
   {!data?.subscription&&<section className="grid gap-4 md:grid-cols-3">{data?.plans.filter(p=>p.amount>0).map(plan=><button key={plan.key} onClick={()=>setSelectedPlan(plan.key)} className={`text-left rounded-2xl border p-5 shadow-sm transition ${selectedPlan===plan.key?'border-cyan-500 bg-cyan-50 ring-2 ring-cyan-200':'border-slate-200 bg-white hover:border-slate-300'}`}><p className="text-sm font-semibold text-cyan-700">{plan.name}</p><p className="mt-2 text-3xl font-bold text-slate-900">{money(plan.amount)}<span className="text-sm font-medium text-slate-500">/mês</span></p><p className="mt-2 text-sm text-slate-500">{plan.description||'Plano QTECNICO'}</p></button>)}</section>}
   {!data?.subscription&&<section className="mt-5 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-bold">Forma de pagamento</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{(['PIX','CREDIT_CARD','BOLETO'] as const).map(type=><button key={type} onClick={()=>setBillingType(type)} className={`rounded-xl border px-4 py-3 text-sm font-semibold ${billingType===type?'border-cyan-500 bg-cyan-50 text-cyan-700':'border-slate-200 bg-white text-slate-600'}`}>{type==='CREDIT_CARD'?'Cartão de crédito':type==='PIX'?'PIX':'Boleto'}</button>)}</div><button onClick={()=>void subscribe()} disabled={busy} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={17}/>:<CreditCard size={17}/>} Continuar para pagamento</button></section>}
   <section className="mt-5 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><h2 className="font-bold">Histórico de cobranças</h2><p className="text-xs text-slate-500">O status financeiro é atualizado pelo Asaas e pelos Webhooks.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Cobrança</th><th className="px-5 py-3">Valor</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Vencimento</th><th className="px-5 py-3">Pagamento</th><th className="px-5 py-3">Ação</th></tr></thead><tbody>{data?.payments.map(p=><tr key={p.id} className="border-t border-slate-100"><td className="px-5 py-4"><div className="font-semibold">{p.providerPaymentId||`#${p.id}`}</div><div className="text-xs text-slate-500">{p.provider}</div></td><td className="px-5 py-4">{money(p.amount)}</td><td className="px-5 py-4">{statusLabel(p.status)}</td><td className="px-5 py-4">{p.dueAt?new Date(p.dueAt).toLocaleDateString('pt-BR'):'—'}</td><td className="px-5 py-4">{p.paidAt?new Date(p.paidAt).toLocaleDateString('pt-BR'):'—'}</td><td className="px-5 py-4">{p.invoiceUrl?<a href={p.invoiceUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-semibold text-cyan-700">Pagar <ExternalLink size={14}/></a>:'—'}</td></tr>)}</tbody></table>{!data?.payments.length&&<div className="p-8 text-center text-sm text-slate-500">Nenhuma cobrança registrada ainda.</div>}</div></section>
   <p className="mt-4 text-xs text-slate-500">Ambiente de homologação: Asaas Sandbox. Nenhum valor real é movimentado durante este teste.</p>
 </div>;
}
